import { ApiEndpoint } from "./apiDocsTypes";

const UPLOAD_FOLDER_RULES =
  "Folders the web uses: students upload to /avatars/students and kyc/students (PAN image). Teachers use avatars/teacher, kyc/teachers, test-thumbnails, test-videos, thumbnails/live-tests, live-test-videos, bundle-thumbnails, bundle-videos, course/<courseId>, course-intros, products/files, library/<teacherId>, editor-images and editor-videos. Admins use avatars/admin, blog-images, news-coverage, editor-images and editor-videos.";

export const apiDocsSite: ApiEndpoint[] = [
  // Site
  {
    method: "GET",
    route: "/_api/homepage/data",
    description: "Get the home page sections: top test series, popular courses and notes, live test spotlight and popular teachers",
    auth: "none",
    category: "Site",
    usedBy: ["web", "mobile"],
    responseFields: [
      { name: "topMockTests", type: "array", description: "Up to 8 published series, by enrollments in the last 7 days then total students: { id, title, slug, thumbnailUrl, examName, totalTests, price, discountPrice, studentsEnrolled, rating, reviewsCount, views, teacherName, teacherSlug, teacherAvatarUrl, teacherTagline, teacherYearsOfExperience, teacherIsVerified }" },
      { name: "popularCourses", type: "array", description: "Up to 8 published courses by enrollments in the last 30 days: { id, title, slug, thumbnailUrl, price, discountPrice, studentsEnrolled, rating, totalLessons, views, teacher fields }" },
      { name: "featuredCourses", type: "array", description: "Up to 5 hand-picked courses (a fixed list in code): { id, title, slug, thumbnailUrl, price, discountPrice, examName, level, totalLessons, teacherName, teacherAvatarUrl, teacherIsVerified }" },
      { name: "popularNotes", type: "array", description: "Up to 8 published study notes by recent purchases, then views: { id, title, slug, price, totalPurchases, rating, pageCount, views, examName, teacher fields }" },
      { name: "liveTestSpotlight", type: "array", description: "Up to 5 active live tests that have not ended, running ones first: { id, title, examName, price, enrolledCount, maxSeats, hasPrizes, totalPrizePool, startTime, endTime, teacher fields }" },
      { name: "popularTeachers", type: "array", description: "Up to 10 active teachers by revenue and enrollments over the last year: { id, displayName, avatarUrl, slug, isVerified, tagline, testCount, courseCount, productCount, studentCount, targetExams }" },
    ],
    notes: [
      "Takes no parameters.",
      "Each section loads on its own and falls back to an empty list if it fails, so a 200 can contain empty sections.",
      "Bundles are not included. The mobile app loads them from /_api/bundles/list.",
    ],
  },
  {
    method: "GET",
    route: "/_api/homepage/search",
    description: "Search published test series, courses, bundles, study notes and teachers",
    auth: "none",
    category: "Site",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "q", type: "string", required: true, description: "Search text. Case-insensitive match on titles, descriptions and teacher names, plus subject and exam names for test series" },
      { name: "limit", type: "number", required: false, description: "Items per group for tests, courses, bundles and products. Default 5, maximum 10. Teachers are always capped at 5" },
    ],
    responseFields: [
      { name: "tests", type: "array", description: "Published series that are not live tests: { id, slug, title, thumbnailUrl, price, discountPrice, examName, category, views, type: 'test', teacher fields }" },
      { name: "courses", type: "array", description: "Published courses: { id, slug, title, thumbnailUrl, price, discountPrice, category, views, type: 'course', teacher fields }" },
      { name: "bundles", type: "array", description: "Published bundles: { id, slug, title, thumbnailUrl, price, originalPrice, itemCount, type: 'bundle', teacher fields }" },
      { name: "products", type: "array", description: "Published study notes: { id, slug, title, thumbnailUrl, price, examName, category, views, type: 'product', teacher fields }" },
      { name: "teachers", type: "array", description: "Up to 5 active teachers with published content: { id, displayName, avatarUrl, slug, isVerified, testCount, courseCount, studentCount }" },
      { name: "totalResults", type: "number", description: "Items across all five groups" },
    ],
    notes: [
      "Returns 400 when q is missing or empty, or limit is not a number or is above 10.",
      "Live tests are not searched.",
    ],
  },
  {
    method: "GET",
    route: "/_api/meta",
    description: "Get site settings such as the latest and minimum supported mobile app version",
    auth: "none",
    category: "Site",
    usedBy: ["mobile"],
    queryParams: [
      { name: "fields", type: "string", required: false, description: "Comma-separated setting names, e.g. 'latestversion,minversion'. When omitted, every setting is returned" },
    ],
    responseFields: [
      { name: "<field name>", type: "string", description: "One key per requested name, null when the setting does not exist. The app reads latestversion and minversion" },
    ],
    notes: [
      "The mobile app forces an update when its version is below minversion, and shows latestversion on the update screen.",
      "Without fields, the whole settings table is public, so never store anything private in it.",
      "Any failure returns 400.",
    ],
  },
  {
    method: "GET",
    route: "/_api/static-page",
    description: "Get an admin-managed static page such as the terms, privacy or refund policy",
    auth: "none",
    category: "Site",
    usedBy: ["web"],
    queryParams: [
      { name: "slug", type: "string", required: true, description: "Page slug. The site uses 'privacy', 'terms' and 'refund'" },
    ],
    responseFields: [
      { name: "id", type: "number", description: "Page id" },
      { name: "slug", type: "string", description: "Page slug" },
      { name: "title", type: "string", description: "Page title" },
      { name: "content", type: "string", description: "Page body as HTML" },
      { name: "updatedAt", type: "Date", description: "Last edit time, may be null" },
    ],
    notes: ["Returns 400 when slug is missing and 404 when no page has it."],
  },
  {
    method: "POST",
    route: "/_api/contact/submit",
    description: "Submit the website contact form",
    auth: "none",
    category: "Site",
    usedBy: ["web"],
    bodyParams: [
      { name: "name", type: "string", required: true, description: "1 to 100 characters" },
      { name: "email", type: "string", required: true, description: "Valid email, up to 255 characters" },
      { name: "subject", type: "string", required: false, description: "Up to 255 characters" },
      { name: "message", type: "string", required: true, description: "1 to 5000 characters" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "Always true on success" },
      { name: "submissionId", type: "number", description: "Id of the stored submission" },
    ],
    notes: [
      "Stores the submission, emails an acknowledgement to the sender and alerts the team inbox.",
      "Returns 400 for invalid input. No sign-in, captcha or rate limit.",
    ],
  },
  {
    method: "POST",
    route: "/_api/demo-request/submit",
    description: "Book a sales demo call from the website popup, creating or updating a sales lead",
    auth: "none",
    category: "Site",
    usedBy: ["web"],
    bodyParams: [
      { name: "name", type: "string", required: true, description: "2 to 100 characters" },
      { name: "phone", type: "string", required: true, description: "10-digit Indian mobile number starting 6-9. Spaces, +91 and a leading 0 are removed" },
      { name: "email", type: "string", required: false, description: "Valid email or empty" },
      { name: "expertise", type: "'School' | 'College' | 'Government Exams' | 'Competitive Exams' | 'Skills' | 'Language' | 'Other'", required: true, description: "What the visitor teaches" },
      { name: "preferredDate", type: "string", required: true, description: "YYYY-MM-DD in IST, from today to 14 days ahead, Monday to Saturday" },
      { name: "preferredSlot", type: "'10:00' | '11:00' | '12:00' | '13:00' | '14:00' | '15:00' | '16:00' | '17:00' | '18:00'", required: true, description: "Start of the one-hour call window in IST" },
      { name: "pageUrl", type: "string", required: false, description: "Page the popup was opened from, up to 500 characters" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "Always true on success" },
      { name: "alreadyInPipeline", type: "boolean", description: "True when an existing lead was updated instead of a new one created" },
    ],
    notes: [
      "Returns 400 for invalid input, including a slot that started more than 30 minutes ago.",
      "When no user matches the phone or email, a teacher account is created (unverified, free plan). The visitor signs in later with a mobile code.",
      "Creates or updates the sales lead and sets its follow-up date, then alerts the admins. No sign-in, captcha or rate limit.",
    ],
  },
  {
    method: "GET",
    route: "/_api/upload-limits",
    description: "Get the admin-configured maximum upload size in MB for each kind of file",
    auth: "none",
    category: "Site",
    usedBy: ["web"],
    responseFields: [
      { name: "thumbnailMaxMb", type: "number", description: "Thumbnail images" },
      { name: "profilePictureMaxMb", type: "number", description: "Profile photos" },
      { name: "kycDocumentMaxMb", type: "number", description: "PAN card images" },
      { name: "coursePdfMaxMb", type: "number", description: "Course and library PDFs" },
      { name: "courseIntroVideoMaxMb", type: "number", description: "Course intro videos" },
      { name: "lessonVideoMaxMb", type: "number", description: "Lesson and library videos" },
      { name: "digitalProductPdfMaxMb", type: "number", description: "Study note PDFs" },
      { name: "richTextImageMaxMb", type: "number", description: "Images in the rich text editor" },
    ],
    notes: [
      "Takes no parameters. These are the limits the upload endpoints enforce. Admins can change them.",
      "Folders that match none of these kinds have no size limit.",
    ],
  },
  {
    method: "POST",
    route: "/_api/analytics/track",
    description: "Record a storefront view, add-to-cart or share event for a published item",
    auth: "optional",
    category: "Site",
    usedBy: ["web"],
    bodyParams: [
      { name: "event", type: "'view' | 'add_to_cart' | 'share'", required: true, description: "Event type" },
      { name: "entity", type: "'mock_test' | 'live_test' | 'course' | 'digital_product' | 'bundle' | 'teacher_profile'", required: true, description: "Kind of item" },
      { name: "id", type: "number", required: false, description: "Item id. Send id or slug" },
      { name: "slug", type: "string", required: false, description: "Item slug, up to 200 characters. Not used for live tests" },
      { name: "sessionId", type: "string", required: true, description: "Browser session id, 8 to 64 characters of letters, digits, _ and -, used to remove duplicates" },
      { name: "utmSource", type: "string", required: false, description: "Campaign source. Lowercased and cut to 60 characters" },
      { name: "utmMedium", type: "string", required: false, description: "Campaign medium. Same cleaning" },
      { name: "utmCampaign", type: "string", required: false, description: "Campaign name. Same cleaning" },
      { name: "referrerHost", type: "string", required: false, description: "Referrer hostname" },
      { name: "device", type: "'mobile' | 'tablet' | 'desktop'", required: false, description: "Device class" },
      { name: "platform", type: "'whatsapp' | 'facebook' | 'x' | 'telegram' | 'linkedin' | 'email' | 'copy'", required: false, description: "Share target, for share events" },
      { name: "campaign", type: "string", required: false, description: "Share campaign, for share events" },
    ],
    responseFields: [
      { name: "ok", type: "boolean", description: "Always true when the call was accepted" },
    ],
    notes: [
      "Works signed out. For views and add-to-cart it reads the session when present, and skips events from admins and from the item's own teacher.",
      "Always answers 200 { ok: true }, even when the item is unknown or the event is skipped. Only a malformed body returns 400.",
      "Events are counted once per session, event, item and hour. No IP address or user agent is stored.",
    ],
  },
  {
    method: "GET",
    route: "/_api/sitemap",
    description: "Get the XML sitemap of public pages for search engines",
    auth: "none",
    category: "Site",
    usedBy: [],
    responseFields: [
      { name: "(xml)", type: "application/xml", description: "A sitemap of static pages, indexable test series, courses, study notes and bundles, teacher profiles, exam pages, live tests, blog and help articles, careers and news" },
    ],
    notes: [
      "Read by search engines through robots.txt. The response is XML, not superjson.",
      "Cached publicly for an hour. A failure returns 500 with a plain text body.",
    ],
  },
  {
    method: "GET",
    route: "/_api/sitemap-media",
    description: "Get the XML image and video sitemap for search engines",
    auth: "none",
    category: "Site",
    usedBy: [],
    responseFields: [
      { name: "(xml)", type: "application/xml", description: "Image and video entries (thumbnails and intro videos) under each indexable item's page, plus blog and help article images" },
    ],
    notes: ["Read by search engines through robots.txt. Same caching as /_api/sitemap."],
  },
  {
    method: "GET",
    route: "/_api/well-known/apple-app-site-association",
    description: "Return the Apple app site association text stored in the database",
    auth: "none",
    category: "Site",
    usedBy: [],
    deprecated: "iOS reads the static file at https://testkart.in/.well-known/apple-app-site-association, not this route, and nothing else calls it. Both still hold a placeholder app id, so iOS universal links do not work yet.",
    responseFields: [
      { name: "(json)", type: "application/json", description: "The stored text, not superjson, or {} when nothing is stored" },
    ],
  },

  // Uploads
  {
    method: "POST",
    route: "/_api/upload/presign",
    description: "Get a presigned URL to upload one file of up to 5 MiB straight to storage",
    auth: "any",
    category: "Uploads",
    usedBy: ["web"],
    bodyParams: [
      { name: "fileName", type: "string", required: true, description: "Original file name. Only the extension is kept in the key" },
      { name: "contentType", type: "string", required: true, description: "MIME type, e.g. 'image/png'. Checked only under library/ and products/" },
      { name: "folder", type: "string", required: true, description: "Target folder, e.g. 'course/123'" },
      { name: "fileSize", type: "number", required: true, description: "Size in bytes, checked against the folder's limit from /_api/upload-limits" },
    ],
    responseFields: [
      { name: "presignedUrl", type: "string", description: "URL to PUT the file to with the same Content-Type, valid for 1 hour" },
      { name: "key", type: "string", description: "Storage key, '<folder>/<uuid>.<ext>'" },
      { name: "publicUrl", type: "string", description: "https://cdn.testkart.in/<key>, or a 10-minute signed link for kyc/ keys" },
    ],
    notes: [
      "Any signed-in user or the admin panel session. Returns 401 otherwise.",
      "Only the kyc folders are tied to a role: kyc/students needs a student and kyc/teachers needs a teacher (403 otherwise).",
      UPLOAD_FOLDER_RULES,
      "library/ accepts only MP4, WebM, MOV and PDF, and products/ only PDF. A file over the folder's limit returns 400.",
      "The web switches to the multipart endpoints for files over 5 MiB. The mobile app does not upload files.",
    ],
  },
  {
    method: "POST",
    route: "/_api/upload/multipart/initiate",
    description: "Start a resumable multipart upload for a large file and get a presigned URL for every part",
    auth: "any",
    category: "Uploads",
    usedBy: ["web"],
    bodyParams: [
      { name: "fileName", type: "string", required: true, description: "Original file name" },
      { name: "contentType", type: "string", required: true, description: "MIME type" },
      { name: "folder", type: "string", required: true, description: "Target folder. Same rules as /_api/upload/presign" },
      { name: "fileSize", type: "number", required: true, description: "Size in bytes, checked against the folder's limit" },
      { name: "partSize", type: "number", required: false, description: "5 MiB to 100 MiB, default 50 MiB. Every part except the last must be this size" },
    ],
    responseFields: [
      { name: "uploadId", type: "string", description: "Pass to the parts and complete endpoints" },
      { name: "key", type: "string", description: "Storage key of the final file" },
      { name: "publicUrl", type: "string", description: "Link to the file once complete" },
      { name: "partSize", type: "number", description: "Part size in use" },
      { name: "parts", type: "array", description: "{ partNumber, presignedUrl } for every part, numbered from 1, each valid for 1 hour" },
    ],
    notes: [
      "Same sign-in, folder, type and size rules as /_api/upload/presign.",
      "Returns 400 when the file would need more than 10000 parts.",
    ],
  },
  {
    method: "POST",
    route: "/_api/upload/multipart/parts",
    description: "List the parts already stored for a multipart upload and get fresh URLs for the missing ones",
    auth: "any",
    category: "Uploads",
    usedBy: ["web"],
    bodyParams: [
      { name: "key", type: "string", required: true, description: "Key from multipart/initiate" },
      { name: "uploadId", type: "string", required: true, description: "Upload id from multipart/initiate" },
      { name: "partNumbers", type: "array", required: true, description: "Part numbers that still need URLs, 1 to 10000" },
    ],
    responseFields: [
      { name: "uploadedParts", type: "array", description: "{ partNumber, size } for parts already stored" },
      { name: "urls", type: "array", description: "{ partNumber, presignedUrl } for each requested part not yet stored" },
    ],
    notes: [
      "Used to resume after a dropped connection or an expired URL.",
      "Returns 404 when the upload was not started by the caller, or is finished, aborted or expired. Returns 401 when signed out.",
    ],
  },
  {
    method: "POST",
    route: "/_api/upload/multipart/complete",
    description: "Finish a multipart upload once all parts are stored",
    auth: "any",
    category: "Uploads",
    usedBy: ["web"],
    bodyParams: [
      { name: "key", type: "string", required: true, description: "Key from multipart/initiate" },
      { name: "uploadId", type: "string", required: true, description: "Upload id from multipart/initiate" },
      { name: "partCount", type: "number", required: false, description: "Expected number of parts. When sent, the upload only completes if exactly this many are stored" },
    ],
    responseFields: [
      { name: "publicUrl", type: "string", description: "Link to the finished file" },
    ],
    notes: [
      "Returns 404 when the upload is not the caller's or is gone, 409 when parts are still missing, and 400 when nothing was uploaded.",
      "Safe to retry after a lost response.",
    ],
  },
  {
    method: "POST",
    route: "/_api/upload/delete",
    description: "Delete a previously uploaded file from storage",
    auth: "teacher",
    category: "Uploads",
    usedBy: ["web"],
    bodyParams: [
      { name: "key", type: "string", required: true, description: "Storage key of the file" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "True when deleted, false when kept because content still uses it" },
      { name: "message", type: "string", description: "'File deleted successfully' or 'File kept because it is still in use'" },
    ],
    notes: [
      "Teachers, admin-role accounts and the admin panel session. Students get 403. Returns 401 when signed out.",
      "A teacher can only delete files their account uploaded (403 otherwise), and a file still used by any content is kept with success false.",
      "Admins can delete any key.",
    ],
  },

  // Blog and news
  {
    method: "GET",
    route: "/_api/blog/list",
    description: "List published blog posts or help articles with search, category and tag filters",
    auth: "none",
    category: "Blog and news",
    usedBy: ["web"],
    queryParams: [
      { name: "type", type: "'blog' | 'knowledge_base'", required: false, description: "Default 'blog'. Help articles are 'knowledge_base' and live in the same table" },
      { name: "categorySlug", type: "string", required: false, description: "Only posts in this category" },
      { name: "search", type: "string", required: false, description: "Case-insensitive match on title and excerpt" },
      { name: "tag", type: "string", required: false, description: "Only posts with this tag slug" },
      { name: "page", type: "number", required: false, description: "Page number, default 1" },
      { name: "limit", type: "number", required: false, description: "1 to 100, default 12" },
    ],
    responseFields: [
      { name: "posts", type: "array", description: "Featured first, then newest: { id, title, slug, excerpt, type, categoryName, categorySlug, featuredImage, publishedAt, readingTimeMinutes, viewCount, authorName, authorAvatar, isFeatured, tags }" },
      { name: "total", type: "number", description: "Posts matching the filters" },
      { name: "totalPages", type: "number", description: "Number of pages" },
    ],
    notes: ["Only published posts. Every failure, including bad parameters, returns 400."],
  },
  {
    method: "GET",
    route: "/_api/blog/post",
    description: "Get one published blog post or help article by slug",
    auth: "none",
    category: "Blog and news",
    usedBy: ["web"],
    queryParams: [
      { name: "slug", type: "string", required: true, description: "Post slug. Works for blog posts and help articles" },
    ],
    responseFields: [
      { name: "post", type: "object", description: "{ id, title, slug, excerpt, content (HTML), type, status, featuredImage, ogImage, seoTitle, seoDescription, isFeatured, readingTimeMinutes, viewCount, authorId, categoryId, publishedAt, createdAt, updatedAt, categoryName, categorySlug, authorName, authorAvatar, tags }" },
    ],
    notes: [
      "Each call increments viewCount.",
      "An unknown or unpublished slug returns 400 'Post not found', not 404.",
    ],
  },
  {
    method: "GET",
    route: "/_api/blog/categories",
    description: "List blog or help article categories with their published post counts",
    auth: "none",
    category: "Blog and news",
    usedBy: ["web"],
    queryParams: [
      { name: "type", type: "'blog' | 'knowledge_base'", required: false, description: "Default 'blog'" },
    ],
    responseFields: [
      { name: "categories", type: "array", description: "By sortOrder: { id, name, slug, type, description, icon, sortOrder, createdAt, updatedAt, postCount }" },
    ],
    notes: ["postCount counts published posts only. Empty categories are still listed."],
  },
  {
    method: "GET",
    route: "/_api/blog/comments/list",
    description: "List approved comments on a blog post, oldest first",
    auth: "none",
    category: "Blog and news",
    usedBy: ["web"],
    queryParams: [
      { name: "postId", type: "number", required: true, description: "Post id" },
    ],
    responseFields: [
      { name: "comments", type: "array", description: "Flat list of { id, postId, userId, parentId, content, status, createdAt, updatedAt, authorName, authorAvatar }. Build threads from parentId" },
    ],
    notes: ["Only approved comments. Any failure returns 400."],
  },
  {
    method: "POST",
    route: "/_api/blog/comments/create",
    description: "Post a comment or reply on a blog post, held for moderation",
    auth: "any",
    category: "Blog and news",
    usedBy: ["web"],
    bodyParams: [
      { name: "postId", type: "number", required: true, description: "Id of a published post" },
      { name: "content", type: "string", required: true, description: "Comment text" },
      { name: "parentId", type: "number", required: false, description: "Id of an approved comment on the same post, to reply to it" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "Always true on success" },
      { name: "comment", type: "object", description: "{ id, postId, userId, parentId, content, status, createdAt, updatedAt }" },
    ],
    notes: [
      "New comments are 'pending' and only show after an admin approves them.",
      "Every failure returns 400, including a missing session.",
    ],
  },
  {
    method: "GET",
    route: "/_api/blog/reactions",
    description: "Get like and dislike counts for a post and this browser's own reaction",
    auth: "none",
    category: "Blog and news",
    usedBy: ["web"],
    queryParams: [
      { name: "postId", type: "number", required: true, description: "Post id" },
      { name: "sessionId", type: "string", required: false, description: "Anonymous browser id. When sent, userReaction reports that browser's reaction" },
    ],
    responseFields: [
      { name: "likes", type: "number", description: "Number of likes" },
      { name: "dislikes", type: "number", description: "Number of dislikes" },
      { name: "userReaction", type: "'like' | 'dislike' | null", description: "Reaction stored for the sessionId" },
    ],
    notes: ["Reactions are anonymous. The web keeps sessionId in the browser's local storage."],
  },
  {
    method: "POST",
    route: "/_api/blog/react",
    description: "Like or dislike a post anonymously, toggling or switching this browser's reaction",
    auth: "none",
    category: "Blog and news",
    usedBy: ["web"],
    bodyParams: [
      { name: "postId", type: "number", required: true, description: "Post id" },
      { name: "sessionId", type: "string", required: true, description: "Anonymous browser id, 1 to 64 characters" },
      { name: "reaction", type: "'like' | 'dislike'", required: true, description: "The reaction" },
    ],
    responseFields: [
      { name: "likes", type: "number", description: "Updated likes" },
      { name: "dislikes", type: "number", description: "Updated dislikes" },
      { name: "userReaction", type: "'like' | 'dislike' | null", description: "Reaction after the change, null when removed" },
    ],
    notes: ["The same reaction again removes it, and the other one switches it. No sign-in or rate limit."],
  },
  {
    method: "GET",
    route: "/_api/news/list",
    description: "List published news coverage, newest first",
    auth: "none",
    category: "Blog and news",
    usedBy: ["web"],
    responseFields: [
      { name: "items", type: "array", description: "{ id, title, slug, publicationName, imageUrl, excerpt, publishedAt }" },
    ],
    notes: ["Takes no parameters and is not paged."],
  },
  {
    method: "GET",
    route: "/_api/news/details",
    description: "Get one published news coverage item by slug, including renamed slugs",
    auth: "none",
    category: "Blog and news",
    usedBy: ["web"],
    queryParams: [
      { name: "slug", type: "string", required: true, description: "Current or earlier slug of the item" },
    ],
    responseFields: [
      { name: "item", type: "object", description: "{ id, title, slug, publicationName, imageUrl, imageFileId, excerpt, writeup (HTML), keywords, coverageUrl, previousSlugs, isPublished, publishedAt, createdAt, updatedAt }" },
    ],
    notes: [
      "An old slug returns the item with its current slug. Compare item.slug with the request and redirect to it.",
      "Returns 404 when nothing is published under the slug. A missing slug returns 500.",
    ],
  },

  // Careers
  {
    method: "GET",
    route: "/_api/careers/list",
    description: "List active career postings",
    auth: "none",
    category: "Careers",
    usedBy: ["web"],
    responseFields: [
      { name: "careers", type: "array", description: "By orderIndex, then newest: { id, slug, title, department, location, employmentType, experienceLevel, salaryRange, description, requirements, orderIndex, isActive, createdAt, updatedAt }" },
    ],
    notes: ["Takes no parameters and is not paged."],
  },
  {
    method: "GET",
    route: "/_api/careers/details",
    description: "Get one active career posting by slug",
    auth: "none",
    category: "Careers",
    usedBy: ["web"],
    queryParams: [
      { name: "slug", type: "string", required: true, description: "Posting slug" },
    ],
    responseFields: [
      { name: "career", type: "object", description: "Same fields as an item in /_api/careers/list" },
    ],
    notes: ["Returns 400 when slug is missing and 404 when no active posting has it."],
  },
  {
    method: "POST",
    route: "/_api/careers/upload-resume",
    description: "Get a presigned URL to upload an applicant's resume",
    auth: "none",
    category: "Careers",
    usedBy: ["web"],
    bodyParams: [
      { name: "fileName", type: "string", required: true, description: "Original file name. Only the extension is kept" },
      { name: "contentType", type: "string", required: true, description: "PDF, DOC, DOCX, JPEG or PNG MIME type" },
      { name: "fileSize", type: "number", required: true, description: "Size in bytes, at most 10 MB" },
    ],
    responseFields: [
      { name: "presignedUrl", type: "string", description: "URL to PUT the file to with the same Content-Type, valid for 1 hour" },
      { name: "key", type: "string", description: "'resumes/<uuid>.<ext>'" },
      { name: "publicUrl", type: "string", description: "Public link to the file. Pass it to /_api/careers/apply as resumeUrl" },
    ],
    notes: [
      "No sign-in. Returns 400 for a disallowed type or a file over 10 MB.",
      "The uploaded resume can be read by anyone who has the link.",
    ],
  },
  {
    method: "POST",
    route: "/_api/careers/apply",
    description: "Apply for an active career posting",
    auth: "none",
    category: "Careers",
    usedBy: ["web"],
    bodyParams: [
      { name: "careerPostingId", type: "number", required: true, description: "Id of an active posting" },
      { name: "name", type: "string", required: true, description: "1 to 100 characters" },
      { name: "email", type: "string", required: true, description: "Valid email" },
      { name: "phone", type: "string", required: false, description: "Phone number" },
      { name: "coverLetter", type: "string", required: false, description: "Cover letter text" },
      { name: "resumeUrl", type: "string", required: false, description: "Usually the publicUrl from /_api/careers/upload-resume" },
      { name: "resumeFileId", type: "string", required: false, description: "Storage key of the resume" },
      { name: "linkedinUrl", type: "string", required: false, description: "LinkedIn profile URL" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "True when saved and emailed" },
      { name: "message", type: "string", description: "'Application submitted successfully'" },
    ],
    notes: [
      "Returns 404 for a missing or inactive posting.",
      "The application is saved, then emailed to the hiring inbox. If the email fails it returns 500 although the application is already saved.",
      "Validation errors return 500, not 400. No sign-in, captcha or rate limit.",
    ],
  },

  // Certificates
  {
    method: "GET",
    route: "/_api/student/certificates/list",
    description: "List the signed-in student's issued certificates",
    auth: "student",
    category: "Certificates",
    usedBy: ["web"],
    responseFields: [
      { name: "certificates", type: "array", description: "Newest first: { id, certificateNumber, certificateType, completionDate, issuedAt, scorePercentage, itemName }" },
    ],
    notes: ["Returns 403 for non-students. A signed-out call returns 500 with details 'Not authenticated'."],
  },
  {
    method: "POST",
    route: "/_api/student/certificate/generate",
    description: "Issue a certificate for a finished course or a completed test and return it as a PDF",
    auth: "student",
    category: "Certificates",
    usedBy: ["web"],
    bodyParams: [
      { name: "certificateType", type: "'course_completion' | 'test_completion'", required: true, description: "Kind of certificate" },
      { name: "itemId", type: "number", required: true, description: "Course id for course_completion, or test item id for test_completion" },
    ],
    responseFields: [
      { name: "(file)", type: "application/pdf", description: "The certificate PDF, named certificate-<number>.pdf" },
    ],
    notes: [
      "A course needs 100 percent completion. A test needs at least one completed attempt with a score. There is no pass mark, and the best score is stored.",
      "One certificate per student and item. A repeat returns 400. Use /_api/student/certificate/download to get it again.",
      "The number has the form CERT-<year>-<6 digits>. The student is emailed when they have an email address.",
      "Returns 403 for non-students and 404 for an unknown test item. Other failures return 500.",
    ],
  },
  {
    method: "POST",
    route: "/_api/student/certificate/download",
    description: "Download one of the signed-in student's certificates as a PDF",
    auth: "student",
    category: "Certificates",
    usedBy: ["web"],
    bodyParams: [
      { name: "certificateId", type: "number", required: true, description: "Numeric certificate id from /_api/student/certificates/list" },
    ],
    responseFields: [
      { name: "(file)", type: "application/pdf", description: "The certificate PDF" },
    ],
    notes: ["Returns 403 for non-students or another student's certificate and 404 for an unknown id."],
  },
  {
    method: "GET",
    route: "/_api/certificate/public",
    description: "Verify a certificate publicly by its certificate number",
    auth: "none",
    category: "Certificates",
    usedBy: ["web"],
    queryParams: [
      { name: "certificateId", type: "string", required: true, description: "The certificate number, e.g. CERT-2026-000123, not the numeric id" },
    ],
    responseFields: [
      { name: "id", type: "number", description: "Certificate id" },
      { name: "certificateNumber", type: "string", description: "Certificate number" },
      { name: "studentName", type: "string", description: "Student display name" },
      { name: "itemName", type: "string", description: "Course or test title" },
      { name: "certificateType", type: "'course_completion' | 'test_completion'", description: "Kind of certificate" },
      { name: "completionDate", type: "Date", description: "Completion date" },
      { name: "scorePercentage", type: "string", description: "Best score for test certificates, null for courses" },
      { name: "issuedBy", type: "string", description: "Teacher academy name, teacher name, or 'Testkart'" },
    ],
    notes: [
      "Despite its name, the certificateId parameter is the certificate number.",
      "Returns 400 when it is missing and 404 when no certificate has that number.",
    ],
  },
  {
    method: "POST",
    route: "/_api/certificate/public-download",
    description: "Download a certificate PDF by its certificate number",
    auth: "none",
    category: "Certificates",
    usedBy: ["web"],
    bodyParams: [
      { name: "certificateId", type: "string", required: true, description: "The certificate number, not the numeric id" },
    ],
    responseFields: [
      { name: "(file)", type: "application/pdf", description: "The certificate PDF" },
    ],
    notes: ["Returns 404 for an unknown number. Other failures, including a bad body, return 500."],
  },

  // Webhooks and jobs
  {
    method: "POST",
    route: "/_api/webhooks/mux",
    description: "Receive Mux video events and update the status of DRM lesson videos",
    auth: "signature",
    category: "Webhooks and jobs",
    usedBy: [],
    bodyParams: [
      { name: "type", type: "string", required: true, description: "Mux event type. video.asset.ready, video.asset.errored and video.asset.deleted are handled. Others are accepted and ignored" },
      { name: "id", type: "string", required: false, description: "Mux event id" },
      { name: "data", type: "object", required: true, description: "{ id (the Mux asset id), status, passthrough, errors }" },
    ],
    responseFields: [
      { name: "received", type: "boolean", description: "Always true when the event was accepted" },
    ],
    notes: [
      "Mux calls it. The body and response are plain JSON, not superjson.",
      "The Mux-Signature header (t=<seconds>,v1=<hex>) must be an HMAC-SHA256 of '<t>.<raw body>' with the webhook secret, within 5 minutes of the server clock. Otherwise 401.",
      "Returns 503 when the webhook secret is not configured, 400 for a bad payload and 500 when the update fails, so Mux retries.",
      "The Mux DRM setup is dormant until its credentials are set, so no events are expected yet.",
    ],
  },
  {
    method: "POST",
    route: "/_api/maintenance/approve-review-temp",
    description: "Retired one-off maintenance route",
    auth: "none",
    category: "Webhooks and jobs",
    usedBy: [],
    deprecated: "Use the admin Content reviews screen instead. The route is still registered, but its code was removed after a single use, so every call fails with 500. It can be deleted.",
    responseFields: [],
  },
];
