import { ApiEndpoint } from "./apiDocsTypes";

export const apiDocsTests: ApiEndpoint[] = [
  // Tests
  {
    method: "GET",
    route: "/_api/tests/list",
    description: "List published mock test series with filters, sorting and paging",
    auth: "optional",
    category: "Tests",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "search", type: "string", required: false, description: "Case-insensitive match on title, description, subject, creator name and exam name" },
      { name: "examId", type: "number", required: false, description: "Keeps series whose primary or additional exam is this exam. A non-numeric value causes a 500" },
      { name: "language", type: "string", required: false, description: "Comma-separated languages, e.g. 'English,Hindi'. A series matches if its language equals any of them" },
      { name: "priceType", type: "'free' | 'paid' | 'all'", required: false, description: "'free' keeps list price 0, 'paid' keeps list price above 0. Anything else applies no price filter" },
      { name: "minPrice", type: "number", required: false, description: "Minimum list price. Only applied when priceType is 'paid'" },
      { name: "maxPrice", type: "number", required: false, description: "Maximum list price. Only applied when priceType is 'paid'" },
      { name: "sortBy", type: "'newest' | 'price_asc' | 'price_desc' | 'popular' | 'rating'", required: false, description: "Defaults to 'popular' (recent enrollments, then views). Price sorts use the discount price when set" },
      { name: "page", type: "number", required: false, description: "Page number, default 1" },
      { name: "limit", type: "number", required: false, description: "Items per page, default 20, no upper cap" },
    ],
    responseFields: [
      { name: "tests", type: "array", description: "Array of { id, slug, title, description, subject, price, discountPrice, totalQuestions, actualQuestionCount, durationMinutes, thumbnailUrl, introVideoUrl, totalTests, freeTestsCount, creatorName, studentsEnrolled, rating, reviewsCount, examName, examSlug, language, views, isEnrolled, teacherName, teacherIsVerified, teacherAvatarUrl, teacherTagline, teacherYearsOfExperience, teacherSlug }" },
      { name: "pagination", type: "object", description: "{ page, limit, totalCount, totalPages }" },
    ],
    notes: [
      "Only published, non-deleted series are listed. Series that back a live test are excluded.",
      "isEnrolled is true only when a valid session is sent and enrolled in that series. Signed-out callers get false on every row.",
      "With examId, each row shows the requested exam as examName and examSlug, because the mobile app filters on examSlug.",
      "page and limit are not validated. A page below 1 returns 500.",
    ],
  },
  {
    method: "GET",
    route: "/_api/tests/details",
    description: "Get a published mock test series with its test items and the caller's enrollment state",
    auth: "optional",
    category: "Tests",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "slug", type: "string", required: false, description: "Series slug. Required if id is not sent, and wins when both are sent" },
      { name: "id", type: "number", required: false, description: "Series id. Required if slug is not sent" },
    ],
    responseFields: [
      { name: "package", type: "object", description: "{ id, title, description, longDescription, subject, price, discountPrice, examName, examSlug, slug, language, rating, studentsEnrolled, reviewsCount, totalTests, freeTestsCount, thumbnailUrl, introVideoUrl, creatorName, whatYouLearn, requirements, createdAt, updatedAt, isEnrolled, disclaimer, seo, teacherId, teacherName, teacherSlug, teacherIsVerified, teacherAvatarUrl, teacherBio, teacherWebsiteUrl, teacherPublicPhone, teacherPublicEmail, teacherAcademyName, teacherSocialLinks, teacherAwardsCertificates }" },
      { name: "items", type: "array", description: "Non-trashed test items by orderIndex: { id, title, description, durationMinutes, totalQuestions, isFree, orderIndex, createdAt, scheduledDate, subjectWiseTiming, questionWiseTiming, subjects: [{ id, subjectName, actualQuestionCount }] }" },
    ],
    notes: [
      "Returns 400 when neither id nor slug is valid, 404 when the series is missing, deleted or backs a live test, and 403 when it is not published.",
      "Each successful call increments the series view counter.",
      "isEnrolled is true only when a valid session is enrolled in the series.",
    ],
  },
  {
    method: "POST",
    route: "/_api/tests/enroll-free",
    description: "Enroll the signed-in user in a free mock test series",
    auth: "any",
    category: "Tests",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "mockTestId", type: "number", required: true, description: "Id of the free series" },
    ],
    responseFields: [
      { name: "orderId", type: "number", description: "Id of the zero-amount completed order created for the enrollment" },
      { name: "message", type: "string", description: "Confirmation text" },
    ],
    notes: [
      "Teachers get 403. Students and admin-role accounts pass.",
      "Returns 404 when the series is missing, deleted, unpublished or backs a live test, and 400 when it is not free or the user is already enrolled.",
      "A missing session or invalid body returns 500 with details 'Not authenticated' or the validation text.",
      "Creates a completed order, an order item and an enrollment in one transaction, then emails the student and the teacher.",
    ],
  },
  {
    method: "GET",
    route: "/_api/tests/leaderboard",
    description: "Get the ranked best attempts for one test item",
    auth: "optional",
    category: "Tests",
    usedBy: ["web"],
    queryParams: [
      { name: "testItemId", type: "number", required: true, description: "Id of a single test item inside a series, not the series id" },
    ],
    responseFields: [
      { name: "leaderboard", type: "array", description: "One entry per student with a completed attempt: { rank, studentName, score, timeTaken, completedAt, attemptNumber }. score is a percentage and timeTaken is minutes" },
      { name: "currentUserBestRank", type: "object", description: "The signed-in user's own entry in the same shape, or null" },
    ],
    notes: [
      "Returns 400 when testItemId is missing or not a positive integer.",
      "Each student's best attempt counts: highest score, then shortest time (capped at the item's duration).",
      "There is no limit parameter and no paging. Student display names are visible to anyone.",
    ],
  },
  {
    method: "GET",
    route: "/_api/test-items/details",
    description: "Get a single test item's timing, marks and subjects for the web test portal",
    auth: "optional",
    category: "Tests",
    usedBy: ["web"],
    queryParams: [
      { name: "testItemId", type: "number", required: true, description: "Test item id" },
    ],
    responseFields: [
      { name: "item", type: "object", description: "{ id, title, durationMinutes, totalQuestions, totalMarks, positiveMarks, negativeMarks, isFree, calculatorEnabled, orderIndex, scheduledDate, createdAt, subjectWiseTiming, questionWiseTiming, subjects: [{ id, subjectName, durationMinutes, questionCount }] }" },
      { name: "package", type: "object", description: "{ id, title, teacherName } of the parent series" },
    ],
    notes: [
      "Returns 400 for a bad id and 404 when the item does not exist.",
      "When the parent series is unpublished it returns 403 unless the signed-in user is enrolled or the item is free.",
      "The mobile app uses /_api/student/test-item/instructions for the same screen.",
    ],
  },
  {
    method: "GET",
    route: "/_api/tests/by-subject",
    description: "List published mock test series listed under an exam, matched by exam name",
    auth: "optional",
    category: "Tests",
    usedBy: [],
    deprecated: "Use /_api/tests/list with examId instead. Nothing first-party calls it, but it is still live and public. Despite its name it filters by exam name, not subject.",
    queryParams: [
      { name: "examName", type: "string", required: true, description: "Official exam name, matched case-insensitively. Omitting it returns 500, and an empty value returns an empty list" },
    ],
    responseFields: [
      { name: "tests", type: "array", description: "Same row shape as /_api/tests/list, newest first, not paged" },
    ],
  },

  // Test attempts
  {
    method: "GET",
    route: "/_api/student/test-item/instructions",
    description: "Get the pre-test instructions for a test item, with the caller's access and previous attempts",
    auth: "optional",
    category: "Test attempts",
    usedBy: ["mobile"],
    queryParams: [
      { name: "testItemId", type: "number", required: true, description: "Test item id" },
    ],
    responseFields: [
      { name: "testItem", type: "object", description: "{ id, title, description, durationMinutes, totalQuestions, totalMarks, positiveMarks, negativeMarks, isFree, calculatorEnabled, subjectWiseTiming, questionWiseTiming, scheduledDate }" },
      { name: "package", type: "object", description: "{ id, title, teacherName, thumbnailUrl }" },
      { name: "subjects", type: "array", description: "{ id, subjectName, durationMinutes, questionCount, maxAttemptsAllowed, sections: [{ id, sectionName, maxAttemptsAllowed, questionCount }] }" },
      { name: "access", type: "object", description: "{ hasAccess, isFree } for the caller" },
      { name: "previousAttempt", type: "object", description: "{ hasAttempted, attemptCount, lastAttempt: { score, totalQuestions, startedAt, completedAt } | null }" },
    ],
    notes: [
      "Despite the student/ prefix, sign-in is not required. Signed in, hasAccess means enrolled in the series, a free item, or enrolled in the live test for a live test paper. Signed out, only free non-live items have access.",
      "Returns 400 for a bad id, 404 when the item is missing, and 403 when its series is unpublished and the caller has no access.",
      "It does not start an attempt or return questions. The web portal uses /_api/test-items/details instead.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/test-item/questions",
    description: "Fetch the question paper for a test item without answer keys",
    auth: "student",
    category: "Test attempts",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "testItemId", type: "number", required: true, description: "Test item id" },
    ],
    responseFields: [
      { name: "calculatorEnabled", type: "boolean", description: "Whether an on-screen calculator is allowed" },
      { name: "subjectWiseTiming", type: "boolean", description: "True when each subject has its own timer" },
      { name: "questionWiseTiming", type: "boolean", description: "True when each question has its own timer (durationSeconds)" },
      { name: "questions", type: "array", description: "Ordered by subject, section, then question: { id, questionText, questionType, optionA to optionE, paragraphText, paragraphId, matchData (leftItems and rightItems only), positiveMarks, negativeMarks, partialMarking, durationSeconds, subjectId, sectionId, subjectName, subjectOrderIndex, subjectMaxAttemptsAllowed, subjectDurationMinutes, sectionName, sectionOrderIndex, sectionMaxAttemptsAllowed, isAiGenerated, aiGenerationMetadata }. Correct answers, explanations and tolerances are left out" },
    ],
    notes: [
      "Returns 403 for non-students, 403 without access (not enrolled, not a free item, or not enrolled in the live test), and 404 when the item is missing.",
      "For a live test paper it returns 403 before the live test starts and after the 5-minute grace period that follows its end.",
      "Other failures, including a missing session, return 400 with the error message.",
    ],
  },
  {
    method: "POST",
    route: "/_api/student/test-item/start-attempt",
    description: "Start a new attempt on a test item the student can access",
    auth: "student",
    category: "Test attempts",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "testItemId", type: "number", required: true, description: "Test item id" },
    ],
    responseFields: [
      { name: "attemptId", type: "number", description: "Id of the new attempt, for submit-attempt" },
      { name: "startedAt", type: "Date", description: "Server time the attempt started" },
    ],
    notes: [
      "Returns 403 for non-students or without access, 404 when the item is missing, and 403 with the available date when the item's scheduledDate is in the future.",
      "A live test paper can only be started inside the live window and only once per student.",
      "Ordinary tests allow unlimited attempts. Each call creates a new attempt and does not resume an unfinished one.",
      "Other failures, including a missing session, return 400 with the error message.",
    ],
  },
  {
    method: "POST",
    route: "/_api/student/test-item/submit-attempt",
    description: "Submit answers for an attempt, score it and store the result",
    auth: "student",
    category: "Test attempts",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "attemptId", type: "number", required: true, description: "Attempt id from start-attempt. Must belong to the caller and not be submitted yet" },
      { name: "answers", type: "array", required: true, description: "One object per answered question (may be empty), chosen by answerType: { questionId, answerType: 'single', selectedOption: 'A' to 'E' } for single-answer, assertion-reason and comprehension questions; { questionId, answerType: 'multiple', selectedOptions: up to 5 of 'A' to 'E' }; { questionId, answerType: 'numerical', numericalAnswer: number }; { questionId, answerType: 'match', matchAnswers: object mapping each left item (text or zero-based index) to a right item (text or index) }. Leave unanswered questions out" },
    ],
    responseFields: [
      { name: "score", type: "number", description: "Percentage score, 2 decimals" },
      { name: "totalMarks", type: "number", description: "Marks obtained. Can be negative" },
      { name: "maxPossibleMarks", type: "number", description: "Maximum marks, respecting subject and section attempt limits" },
      { name: "totalQuestions", type: "number", description: "Questions in the test item" },
      { name: "correctAnswers", type: "number", description: "Fully correct answers" },
      { name: "timeTakenSeconds", type: "number", description: "Seconds from start to submission" },
      { name: "results", type: "array", description: "Per question: { questionId, questionType, isCorrect, marksObtained, correctOption, selectedOption, correctOptions, selectedOptions, correctNumericalAnswer, studentNumericalAnswer, numericalTolerance, matchData, matchAnswers, explanation }. isCorrect is null for unattempted questions" },
    ],
    notes: [
      "Returns 403 for non-students or another user's attempt, 404 for an unknown attempt, and 400 when it was already submitted.",
      "Returns 400 when more questions are answered than a section or subject limit allows. Answers for questions outside the test are ignored.",
      "Live test papers need a live test enrollment, an attempt started inside the live window, and submission before the end time plus 5 minutes.",
      "Until a live test's submissions close, per-question details in results are hidden (isCorrect null, answer keys and explanations null). Totals are still returned.",
      "Stores the answers in one transaction and emails the student a summary. Ordinary tests have no server-side time limit check.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/test-attempts/latest-results",
    description: "Get the student's latest completed attempt for a test item with per-question results",
    auth: "student",
    category: "Test attempts",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "testItemId", type: "number", required: true, description: "Test item id" },
    ],
    responseFields: [
      { name: "attemptId", type: "number", description: "Latest completed attempt" },
      { name: "score", type: "number", description: "Percentage score" },
      { name: "totalMarks", type: "number", description: "Marks obtained" },
      { name: "maxPossibleMarks", type: "number", description: "Sum of positive marks over all questions (ignores attempt limits)" },
      { name: "correctAnswers", type: "number", description: "Questions marked correct" },
      { name: "totalQuestions", type: "number", description: "Questions in results" },
      { name: "timeTaken", type: "number", description: "Seconds from start to completion" },
      { name: "completedAt", type: "Date", description: "When the attempt was submitted" },
      { name: "mockTestId", type: "number", description: "Parent series id" },
      { name: "testPackageTitle", type: "string", description: "Parent series title" },
      { name: "results", type: "array", description: "Per question: { questionId, questionText, questionType, optionA to optionE, correctOption, correctOptions, correctNumericalAnswer, numericalTolerance, matchData, paragraphText, positiveMarks, negativeMarks, partialMarking, explanation, selectedOption, selectedOptions, studentNumericalAnswer, matchAnswers, isCorrect, marksObtained }" },
    ],
    notes: [
      "Returns 403 for non-students or when the student is not enrolled (unless the item is free), 400 for a bad testItemId, and 404 when the item or a completed attempt is missing.",
      "Until a live test's submissions close, answer keys, explanations and marks are hidden. Totals are still returned.",
      "A missing session returns 500 with details 'Not authenticated'.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/enrolled-tests",
    description: "List the signed-in user's enrolled mock test series with per-item progress",
    auth: "any",
    category: "Test attempts",
    usedBy: ["web", "mobile"],
    responseFields: [
      { name: "enrolledTests", type: "array", description: "Newest enrollment first: { id, title, description, subject, price, thumbnailUrl, examName, examSlug, teacherId, creatorName, totalTests, freeTestsCount, studentsEnrolled, rating, reviewsCount, durationMinutes, totalQuestions, slug, isPublished, enrolledAt, hasReviewed, totalItems, completedItems, progressPercentage, averageScore, testItems: [{ id, title, description, subject, durationMinutes, totalQuestions, isFree, orderIndex, scheduledDate, attemptsCount, completedAttemptsCount, bestScore, lastAttemptedAt, isCompleted }] }. price and rating are numeric strings" },
    ],
    notes: [
      "Takes no parameters and is not paged. The page and limit values the mobile app sends are ignored.",
      "Live test series are excluded. Unpublished series the user is enrolled in are still listed with isPublished false.",
      "A missing session returns 500 with details 'Not authenticated'.",
    ],
  },

  // Live tests
  {
    method: "GET",
    route: "/_api/live-tests/list",
    description: "List active live tests with status, exam and search filters",
    auth: "optional",
    category: "Live tests",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "status", type: "'all' | 'upcoming' | 'live' | 'ended' | 'registration_closed' | 'seats_full'", required: false, description: "Omitted, empty or 'all' hides ended tests. 'ended' returns tests that ended in the last 60 days with at least one enrollment" },
      { name: "examName", type: "string", required: false, description: "Case-insensitive match on the series' exam name or any additional exam name" },
      { name: "examSlug", type: "string", required: false, description: "Keeps live tests listed under that exam" },
      { name: "exam", type: "string", required: false, description: "Alias for examSlug that the shipped mobile app also sends. examSlug wins when both are given" },
      { name: "searchQuery", type: "string", required: false, description: "Case-insensitive match on title, description and teacher name" },
      { name: "page", type: "number", required: false, description: "Page number, default 1" },
      { name: "limit", type: "number", required: false, description: "Items per page, default 10, no upper cap" },
    ],
    responseFields: [
      { name: "tests", type: "array", description: "Sorted live, upcoming, seats_full, registration_closed, ended: { id, title, description, price, discountPrice, startTime, endTime, registrationDeadline, maxSeats, enrolledCount, thumbnailUrl, introVideoUrl, hasPrizes, totalPrizePool, firstPrize, secondPrize, thirdPrize, mockTestId, viewCount, examName, examSlug, teacherName, teacherIsVerified, durationMinutes, actualQuestionCount, subjects, language, status, isEnrolled, hasAttempted }" },
      { name: "total", type: "number", description: "Count after the status filter, before paging" },
      { name: "page", type: "number", description: "Page used" },
      { name: "limit", type: "number", description: "Limit used" },
    ],
    notes: [
      "status is computed at request time from the start and end times, registration deadline and seats.",
      "isEnrolled and hasAttempted are only filled when a valid session is sent. The shipped mobile app calls this without a token, so it always sees false.",
      "Filtering and paging happen in memory after loading every matching live test.",
    ],
  },
  {
    method: "GET",
    route: "/_api/live-tests/details",
    description: "Get one active live test with prize info, teacher profile and the caller's enrollment state",
    auth: "optional",
    category: "Live tests",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "id", type: "number", required: true, description: "Live test id" },
    ],
    responseFields: [
      { name: "(live test fields)", type: "object", description: "One flat object with every live test column: id, title, description, price, discountPrice, startTime, endTime, registrationDeadline, maxSeats, enrolledCount, thumbnailUrl, introVideoUrl, hasPrizes, totalPrizePool, firstPrize, secondPrize, thirdPrize, prizeTiers, prizeDistributionStatus, mockTestId, teacherId, viewCount, isActive, isFree and more" },
      { name: "isEnrolled", type: "boolean", description: "True when the signed-in user is enrolled" },
      { name: "canEnroll", type: "boolean", description: "True when not enrolled, registration is open, the test has not ended and seats remain" },
      { name: "hasAttempted", type: "boolean", description: "True when the signed-in user has any attempt on the live test's papers" },
      { name: "slug", type: "string", description: "Slug of the backing mock test" },
      { name: "examSlug", type: "string", description: "Exam slug, falling back to a slug of the exam name, then 'general-exam'" },
      { name: "teacherSlug", type: "string", description: "Teacher profile slug" },
      { name: "teacherIsVerified", type: "boolean", description: "Whether the teacher is verified" },
      { name: "teacherProfile", type: "object", description: "{ id, name, avatarUrl, bio, websiteUrl, socialLinks, awardsCertificates, publicPhone, publicEmail, academyName }" },
      { name: "mockTestDetails", type: "object", description: "{ id, title, description, examName, durationMinutes, totalQuestions, subject, firstTestItemId }. firstTestItemId is the paper to pass to start-attempt" },
      { name: "disclaimer", type: "string", description: "Standard product disclaimer" },
    ],
    notes: [
      "Returns 400 for a bad id, and 404 when the live test is missing or inactive, or its series has no test items.",
      "Each successful call increments the view count.",
    ],
  },
  {
    method: "POST",
    route: "/_api/live-tests/enroll",
    description: "Enroll the signed-in student in a free live test",
    auth: "student",
    category: "Live tests",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "liveTestId", type: "number", required: true, description: "Live test id" },
      { name: "paymentOrderId", type: "number", required: false, description: "Completed order id for a paid live test. First-party clients never send it, because the PayU callback enrolls paid buyers" },
    ],
    responseFields: [
      { name: "message", type: "string", description: "'Successfully enrolled in the live test.'" },
    ],
    notes: [
      "Returns 403 for non-students. Every other failure is 400: not found, already enrolled, ended, registration closed, full, a paid test without a valid paymentOrderId, or a missing session.",
      "Seats are locked during enrollment, so they cannot be oversold.",
      "Emails the student and the teacher.",
    ],
  },
  {
    method: "POST",
    route: "/_api/live-tests/purchase",
    description: "Create a pending order for a paid live test and return the PayU checkout form fields",
    auth: "student",
    category: "Live tests",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "liveTestId", type: "number", required: true, description: "Live test id" },
      { name: "deepLinkUrl", type: "string", required: false, description: "App link such as 'testkart://payment/callback'. The mobile app sends it, the web does not. It is signed into the PayU request as udf1, and the callback redirects there after payment" },
    ],
    responseFields: [
      { name: "key", type: "string", description: "PayU merchant key" },
      { name: "txnid", type: "string", description: "'live-test-<liveTestId>-<random>'" },
      { name: "amount", type: "string", description: "Amount with 2 decimals, using a valid discount price" },
      { name: "productinfo", type: "string", description: "Live test title, at most 100 characters" },
      { name: "firstname", type: "string", description: "Buyer's display name" },
      { name: "email", type: "string", description: "Buyer's email, or '<mobile>@mail.testkart.in' for phone-only accounts" },
      { name: "phone", type: "string", description: "Fixed placeholder '9999999999'" },
      { name: "surl", type: "string", description: "/_api/payment/payu/callback" },
      { name: "furl", type: "string", description: "/_api/payment/payu/callback" },
      { name: "hash", type: "string", description: "SHA-512 request hash" },
      { name: "payuUrl", type: "string", description: "PayU form action URL" },
      { name: "udf1", type: "string", description: "Echo of deepLinkUrl, only when one was sent" },
    ],
    notes: [
      "Paid live tests only. A free one returns 400 telling the client to use /_api/live-tests/enroll. There is no promo code parameter.",
      "The client posts the fields as a form to payuUrl. The web relays them through POST /_api/payment/payu/redirect and the mobile app submits them from a WebView.",
      "The PayU callback enrolls the student. With deepLinkUrl it redirects to that link with status, order_id, txnid and a fresh session token.",
      "Every failure is 400 { error: 'Failed to initiate payment.', details }, including non-students, a missing session, an ended or full test, a passed deadline and an existing enrollment. Read details.",
      "Cancels the caller's earlier pending orders for the same live test, then creates a new pending order.",
    ],
  },
  {
    method: "GET",
    route: "/_api/live-tests/leaderboard",
    description: "Get the ranked results, prize tiers and the caller's own standing for a live test",
    auth: "optional",
    category: "Live tests",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "liveTestId", type: "number", required: true, description: "Live test id" },
    ],
    responseFields: [
      { name: "leaderboard", type: "array", description: "{ rank, studentName, score, timeTaken }. Empty before the live test starts" },
      { name: "currentUserRank", type: "object", description: "The signed-in user's own entry, or null" },
      { name: "currentUserStatus", type: "'not_enrolled' | 'enrolled_not_attempted' | 'attempted'", description: "The signed-in user's state, or null when signed out" },
      { name: "testStatus", type: "'not_started' | 'ongoing' | 'completed'", description: "Computed from the start and end times" },
      { name: "dynamicPrizes", type: "object", description: "{ tiers: [{ rankFrom, rankTo, amountPerRank }], totalPrizePool, isReduced }, scaled down when paid revenue after the platform fee cannot cover the pool. null when the test has no prizes" },
    ],
    notes: [
      "Returns 400 for a bad liveTestId and 404 when the live test does not exist.",
      "Each enrolled student's first completed attempt counts if it started in the live window and was submitted before the end time plus 5 minutes. Ties go to the shorter time, then the earlier finish. The same ranking drives prize payout.",
      "Not paged. The shipped mobile app calls it without a token, so currentUserRank and currentUserStatus are always null there.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/enrolled-live-tests",
    description: "List the live tests the signed-in user is enrolled in",
    auth: "any",
    category: "Live tests",
    usedBy: ["web"],
    responseFields: [
      { name: "enrolledLiveTests", type: "array", description: "Latest end time first: { id, title, description, thumbnailUrl, price, startTime, endTime, teacherName, enrolledCount, maxSeats, hasPrizes, totalPrizePool, firstPrize, secondPrize, thirdPrize, status, hasAttempted, mockTestId, enrolledAt }. Money fields are numeric strings" },
    ],
    notes: [
      "Takes no parameters and is not paged. Students and admin-role accounts are allowed. Teachers get 403.",
      "A missing session returns 500 with details 'Not authenticated'.",
    ],
  },
  {
    method: "POST",
    route: "/_api/live-tests/distribute-prizes",
    description: "Manually run the prize payout for a finished live test",
    auth: "admin",
    category: "Live tests",
    usedBy: [],
    bodyParams: [
      { name: "liveTestId", type: "number", required: true, description: "Live test id" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "True when the call completed" },
      { name: "message", type: "string", description: "Outcome, e.g. 'Prizes already distributed.'" },
      { name: "distributed", type: "boolean", description: "True only when this call paid out the prizes" },
    ],
    notes: [
      "Needs an admin session with the live tests section. No admin screen calls it. The scheduled prize payout job does the same work automatically.",
      "Fails with 400 until the end time plus 5 minutes has passed. Safe to repeat: a test with no prizes or already paid returns distributed false.",
      "Credits winners' wallets, marks the test distributed and emails winners.",
    ],
  },
  {
    method: "GET",
    route: "/_api/live-tests/check-enrollment",
    description: "Check whether the signed-in student is enrolled in a live test and can still enroll",
    auth: "student",
    category: "Live tests",
    usedBy: [],
    deprecated: "Use /_api/live-tests/details instead, which returns isEnrolled and canEnroll. Nothing first-party calls it, but it is still live.",
    queryParams: [
      { name: "liveTestId", type: "number", required: true, description: "Live test id" },
    ],
    responseFields: [
      { name: "isEnrolled", type: "boolean", description: "True when the student is enrolled" },
      { name: "canEnroll", type: "boolean", description: "True when not enrolled, registration is open and seats remain" },
      { name: "reason", type: "string", description: "Why canEnroll is false, otherwise null" },
    ],
    notes: ["Returns 403 for non-students, 400 for a bad id and 404 for an unknown live test."],
  },

  // Exams
  {
    method: "GET",
    route: "/_api/exams/list",
    description: "List all exam categories with their exams",
    auth: "none",
    category: "Exams",
    usedBy: ["web", "mobile"],
    responseFields: [
      { name: "categories", type: "array", description: "By orderIndex, then name: { id, categoryName, categorySlug, orderIndex, createdAt, exams: [{ id, categoryId, examName, fullName, examSlug, description, orderIndex, createdAt, updatedAt, ownerTag, contentDueDate, aiGenerationPrompt }] }" },
    ],
    notes: [
      "Takes no parameters and is not paged. There is no category or search filter.",
      "Returns every exam column, including internal fields such as ownerTag, contentDueDate and aiGenerationPrompt.",
    ],
  },
  {
    method: "GET",
    route: "/_api/exams/popular-with-tests",
    description: "List the exams with the most published mock test series",
    auth: "none",
    category: "Exams",
    usedBy: ["web"],
    responseFields: [
      { name: "exams", type: "array", description: "At most 24, by series count then name: { id, examName, examSlug, seriesCount }" },
    ],
    notes: ["Takes no parameters. A series counts once under each exam it is listed under."],
  },
  {
    method: "GET",
    route: "/_api/exam-content/get",
    description: "Get the published editorial content page for an exam",
    auth: "none",
    category: "Exams",
    usedBy: ["web"],
    queryParams: [
      { name: "examSlug", type: "string", required: true, description: "Exam slug" },
      { name: "pageType", type: "'overview' | 'syllabus' | 'exam_pattern' | 'eligibility' | 'cutoff' | 'mock_tests' | 'courses' | 'study_notes' | 'bundles'", required: true, description: "Which content section to fetch" },
    ],
    responseFields: [
      { name: "exam", type: "object", description: "{ id, examName, fullName, examSlug, categoryName }" },
      { name: "page", type: "object", description: "{ pageType, title, seoTitle, seoDescription, description, content, faqItems, publishedAt }, or null when the section has no published version" },
      { name: "publishedPageTypes", type: "array", description: "Which of 'syllabus', 'exam_pattern', 'eligibility' and 'cutoff' have a published version" },
    ],
    notes: [
      "Returns 404 for an unknown examSlug. A missing or invalid parameter returns 500, not 400.",
      "Only published content is returned. Drafts never leave the server.",
    ],
  },
  {
    method: "GET",
    route: "/_api/exam-products/counts",
    description: "Count the published products available under an exam",
    auth: "none",
    category: "Exams",
    usedBy: ["web"],
    queryParams: [
      { name: "examSlug", type: "string", required: true, description: "Exam slug" },
    ],
    responseFields: [
      { name: "examId", type: "number", description: "Exam id, or null when the slug is unknown" },
      { name: "counts", type: "object", description: "{ mockTests, digitalProducts, courses, bundles }. Live test series are not counted as mock tests" },
    ],
    notes: ["An unknown slug returns 200 with examId null and zero counts. A missing slug returns 500."],
  },
  {
    method: "POST",
    route: "/_api/exam-focus/save",
    description: "Replace the signed-in user's list of focus exams",
    auth: "any",
    category: "Exams",
    usedBy: ["web"],
    bodyParams: [
      { name: "examIds", type: "array", required: true, description: "1 to 5 exam ids in display order. Duplicates are dropped" },
    ],
    responseFields: [
      { name: "examFocus", type: "array", description: "The saved list in order: { id, examName, examSlug }" },
    ],
    notes: [
      "Students and teacher account owners only. Team managers and other roles get 403. A missing session returns 401.",
      "Returns 400 for an empty or too long list, or an exam that no longer exists.",
      "For teachers it also overwrites the target exams on their profile.",
    ],
  },
  {
    method: "GET",
    route: "/_api/exams/custom-names",
    description: "List free-text exam names that content uses without linking an official exam",
    auth: "none",
    category: "Exams",
    usedBy: ["web"],
    responseFields: [
      { name: "names", type: "array", description: "Distinct exam names, A to Z, from mock test series and study notes with no linked exam" },
    ],
    notes: [
      "Called by the teacher and admin content editors. The returned list is not shown anywhere in the interface today.",
      "Includes names from unpublished series.",
    ],
  },
];
