import { ApiEndpoint } from "./apiDocsTypes";

const PAYU_HASH_NOTE =
  "Hash check: SHA-512 of [additionalCharges|]salt|status||||||udf5|udf4|udf3|udf2|udf1|email|firstname|productinfo|amount|txnid|key must equal hash. On a mismatch nothing changes.";

export const apiDocsCommerce: ApiEndpoint[] = [
  // Cart and orders
  {
    method: "GET",
    route: "/_api/cart/items",
    description: "List the signed-in user's cart items with prices and product details",
    auth: "any",
    category: "Cart and orders",
    usedBy: ["web", "mobile"],
    responseFields: [
      { name: "items", type: "array", description: "Newest first: { type: 'test' | 'course' | 'digitalProduct', cartItemId, slug, title, price, discountPrice, thumbnailUrl }, plus mockTestId and creatorName for tests, courseId, thumbnailImageUrl and teacherName for courses, or digitalProductId for study notes" },
    ],
    notes: [
      "discountPrice is null when no discount is active, and always null for study notes.",
      "A signed-out request returns 500 with details 'Not authenticated'.",
    ],
  },
  {
    method: "POST",
    route: "/_api/cart/add",
    description: "Add a mock test series, course or study note to the signed-in user's cart",
    auth: "any",
    category: "Cart and orders",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "mockTestId", type: "number", required: false, description: "Series id. Send exactly one of mockTestId, courseId or digitalProductId" },
      { name: "courseId", type: "number", required: false, description: "Course id" },
      { name: "digitalProductId", type: "number", required: false, description: "Study note id" },
    ],
    responseFields: [
      { name: "message", type: "string", description: "'Item added to cart successfully.' or 'Item is already in your cart.' (both 200)" },
    ],
    notes: [
      "Teachers get 403. Students and admin-role accounts pass.",
      "Returns 404 when the item is missing or not for sale (unpublished, deleted, or a series that backs a live test), 400 when it is free, and 400 when the user already owns it.",
      "Sending no id or more than one returns 500 with the validation text in details. A signed-out request returns 500 too.",
      "Live tests and bundles cannot be added to the cart. They have their own checkouts.",
    ],
  },
  {
    method: "POST",
    route: "/_api/cart/remove",
    description: "Remove one item from the signed-in user's cart",
    auth: "any",
    category: "Cart and orders",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "cartItemId", type: "number", required: true, description: "The cartItemId from /_api/cart/items, not the product id" },
    ],
    responseFields: [
      { name: "message", type: "string", description: "'Item removed from cart successfully.'" },
    ],
    notes: ["Returns 404 when the cart row does not exist or belongs to someone else. A signed-out request returns 500."],
  },
  {
    method: "GET",
    route: "/_api/orders/list",
    description: "List every order the signed-in student has placed, newest first",
    auth: "student",
    category: "Cart and orders",
    usedBy: ["web", "mobile"],
    responseFields: [
      { name: "orders", type: "array", description: "{ id, createdAt, status: 'pending' | 'completed' | 'failed' | 'cancelled' | 'refunded', totalAmount (decimal text such as '499.00'), itemCount }" },
    ],
    notes: [
      "Not paged and has no total field. The page and limit the mobile app sends are ignored.",
      "Pending, failed and cancelled orders are included. Bundle orders have itemCount 0.",
      "Teachers get 403. Admin-role accounts see their own orders. A signed-out request returns 500.",
    ],
  },
  {
    method: "GET",
    route: "/_api/orders/details",
    description: "Get one of the signed-in user's orders with its items, discount and payment failure reason",
    auth: "any",
    category: "Cart and orders",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "id", type: "number", required: true, description: "Order id. The parameter is named id, not orderId" },
    ],
    responseFields: [
      { name: "id", type: "number", description: "Order id" },
      { name: "status", type: "'pending' | 'completed' | 'failed' | 'cancelled' | 'refunded'", description: "Order status" },
      { name: "subtotal", type: "number", description: "totalAmount plus discountAmount" },
      { name: "discountAmount", type: "number", description: "Promo discount, 0 when none" },
      { name: "promoCode", type: "string", description: "Promo code text, or null" },
      { name: "totalAmount", type: "number", description: "Amount charged" },
      { name: "createdAt", type: "Date", description: "When the order was created" },
      { name: "paymentTransactionId", type: "string", description: "PayU transaction id, or null for free and wallet orders" },
      { name: "items", type: "array", description: "{ orderItemId, itemType: 'test' | 'course' | 'product' | 'bundle', mockTestId, courseId, digitalProductId, bundleId, title, thumbnailUrl, priceAtPurchase }" },
      { name: "paymentFailure", type: "object", description: "{ reason, message } for failed or cancelled orders with a PayU reason, otherwise null" },
    ],
    notes: [
      "The response is the order itself, not wrapped in an order field.",
      "Returns 400 for a bad id and 404 when the order is missing or belongs to someone else. A signed-out request returns 500.",
      "A bundle order gets one synthetic bundle item with orderItemId -1.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/orders/invoice",
    description: "Download the tax invoice PDF for one of the signed-in student's paid orders",
    auth: "student",
    category: "Cart and orders",
    usedBy: ["web"],
    queryParams: [
      { name: "orderId", type: "number", required: true, description: "The student's own order id" },
    ],
    responseFields: [
      { name: "(file)", type: "application/pdf", description: "PDF attachment named invoice-<invoiceNumber>.pdf" },
    ],
    notes: [
      "Returns 403 for non-students and 404 when the order is missing or someone else's.",
      "Returns 400 when the order is not completed, is free, or has no invoice number yet (retry in a few minutes).",
    ],
  },

  // Payments
  {
    method: "GET",
    route: "/_api/payment/payu/redirect",
    description: "Web cart checkout: turn the cart into an order and send the browser to PayU, or complete it at once when the total is zero",
    auth: "any",
    category: "Payments",
    usedBy: ["web"],
    queryParams: [
      { name: "promoCodeId", type: "number", required: false, description: "Promo code id from /_api/promo-codes/validate, not the code text" },
    ],
    responseFields: [
      { name: "(html)", type: "page", description: "An auto-submitting form to PayU, or for a zero total a page that sends the browser to /student/dashboard?order_id=<id>&free=true" },
    ],
    notes: [
      "The cart page navigates the browser here, so the session cookie identifies the user.",
      "Errors are HTML pages with a link back to the cart: 400 for a bad promoCodeId, 500 for an empty cart, an invalid promo code or a missing session.",
      "Cancels the user's other pending orders and creates a new one. A zero total is completed as a free order straight away.",
      "Has no deep link support. The mobile app uses POST /_api/payment/payu/initiate.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/initiate",
    description: "Mobile cart checkout: turn the cart into a pending order and return the PayU form fields",
    auth: "any",
    category: "Payments",
    usedBy: ["mobile"],
    bodyParams: [
      { name: "promoCodeId", type: "number", required: false, description: "Promo code id from /_api/promo-codes/validate, not the code text" },
      { name: "deepLinkUrl", type: "string", required: false, description: "App link such as testkart://payment/callback, signed into the request as udf1 so the callback can return to the app" },
    ],
    responseFields: [
      { name: "key", type: "string", description: "PayU merchant key" },
      { name: "txnid", type: "string", description: "testkart-<12 characters>" },
      { name: "amount", type: "string", description: "Final amount with 2 decimals after the promo discount" },
      { name: "productinfo", type: "string", description: "Item titles, at most 100 characters" },
      { name: "firstname", type: "string", description: "Display name, or 'Student'" },
      { name: "email", type: "string", description: "User email, or <mobile>@mail.testkart.in" },
      { name: "phone", type: "string", description: "Always 9999999999" },
      { name: "surl", type: "string", description: "/_api/payment/payu/callback" },
      { name: "furl", type: "string", description: "/_api/payment/payu/callback" },
      { name: "hash", type: "string", description: "SHA-512 request hash" },
      { name: "payuUrl", type: "string", description: "PayU form action URL" },
      { name: "udf1", type: "string", description: "Echo of deepLinkUrl, only when one was sent" },
    ],
    notes: [
      "The app posts these fields as a form to payuUrl inside a WebView.",
      "Prices come from the database, not the client. The cart is cleared only after payment succeeds. Promo usage is recorded straight away.",
      "Cancels the user's other pending orders first.",
      "With a deep link, the callback ends with a 302 to that link carrying status, order_id, txnid, and on success a fresh 30-day token, on failure a reason.",
      "Every failure returns 500 'Failed to initiate payment.' with the reason in details, including an empty cart, a bad promo code and a missing session.",
      "A 100 percent discount is not special-cased here and produces amount 0.00, while the web redirect completes such orders as free.",
    ],
  },
  {
    method: "GET",
    route: "/_api/payment/payu/bundle-redirect",
    description: "Bundle checkout with an optional promo code: create the order and send the browser to PayU, or complete it at once when free",
    auth: "student",
    category: "Payments",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "bundleId", type: "number", required: true, description: "Id of a published bundle" },
      { name: "promoCodeId", type: "number", required: false, description: "Promo code id, not the code text" },
    ],
    responseFields: [
      { name: "(html)", type: "page", description: "An auto-submitting PayU form, or for a zero total a page that sends the browser to /student/dashboard?order_id=<id>&free=true" },
    ],
    notes: [
      "This is the only route that redeems a promo code against a bundle. Teachers get a 403 page. Admin-role accounts are not rejected.",
      "Errors are HTML pages: 400 for bad parameters, 500 for an unknown bundle, an existing enrollment, a bad promo code or a missing session.",
      "The promo code's minimum purchase amount is not enforced here.",
      "The mobile app loads this URL in a WebView with the bearer header and watches for /_api/payment/payu/callback, because the form has no deep link.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/redirect",
    description: "Relay ready-made PayU form fields back as an auto-submitting page",
    auth: "any",
    category: "Payments",
    usedBy: ["web"],
    bodyParams: [
      { name: "superjsonData", type: "string", required: true, description: "A browser form field (not a JSON body) holding a superjson string of the PayU fields { key, txnid, amount, productinfo, firstname, email, phone, surl, furl, hash, payuUrl } plus optional udf1 to udf5 and standing-instruction fields" },
    ],
    responseFields: [
      { name: "(html)", type: "page", description: "Hidden inputs for every field and a form that submits itself to payuUrl" },
    ],
    notes: [
      "Used after /_api/live-tests/purchase, the teacher sponsorship and subscription checkouts and the autopay sign-up. It works around the page's form-action security policy.",
      "payuUrl must be https://test.payu.in/_payment or https://secure.payu.in/_payment, otherwise 400.",
      "It does not build or check the hash. PayU does that.",
      "Returns a 401 page when signed out and a 400 page for other failures.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/callback",
    description: "PayU result for a student order: verify the hash, settle the order and send the user back to the site or app",
    auth: "signature",
    category: "Payments",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "status", type: "string", required: true, description: "PayU status. 'success' completes the order" },
      { name: "txnid", type: "string", required: true, description: "Transaction id of the pending order" },
      { name: "amount", type: "string", required: true, description: "Amount PayU charged" },
      { name: "productinfo", type: "string", required: true, description: "Echoed by PayU" },
      { name: "firstname", type: "string", required: true, description: "Echoed by PayU" },
      { name: "email", type: "string", required: false, description: "Echoed by PayU" },
      { name: "key", type: "string", required: true, description: "Merchant key" },
      { name: "hash", type: "string", required: true, description: "PayU's SHA-512 response hash" },
      { name: "udf1", type: "string", required: false, description: "Deep link sent at initiate time. udf2 to udf5 are also read for the hash" },
      { name: "unmappedstatus", type: "string", required: false, description: "'userCancelled' marks a Cancel or Back press" },
      { name: "additionalCharges", type: "string", required: false, description: "When present, prefixed to the hash string" },
    ],
    responseFields: [
      { name: "(html)", type: "page", description: "A bridge page that tells the opener window the result or moves the browser to a site URL" },
      { name: "(redirect)", type: "302", description: "Deep link flow only: to the udf1 link with status, order_id, txnid, and token on success or reason on failure" },
    ],
    notes: [
      "PayU posts the browser here as surl and furl. Clients never call it directly. The mobile bundle checkout watches for navigation to this URL.",
      `${PAYU_HASH_NOTE} The browser goes to /cart?error=invalid_hash.`,
      "Success completes the order, clears the cart and creates enrollments, then redirects to /student/dashboard or, for a live test, to its page with status=success.",
      "Cancel sets the order cancelled and redirects to /cart?cancelled=true. Failure sets it failed with PayU's reason, emails the student and redirects to /cart?status=failed.",
      "A repeat callback does not change a settled order. Deep links carry a fresh 30-day session token on success, and the mobile app stores it.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/verify-and-complete",
    description: "Ask PayU for a transaction's real status and complete the matching order if it was paid",
    auth: "none",
    category: "Payments",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "txnid", type: "string", required: false, description: "PayU transaction id. Send txnid or orderId. txnid wins when both are sent" },
      { name: "orderId", type: "number", required: false, description: "Order id. Its stored transaction id is used" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "True when the check ran" },
      { name: "orderStatus", type: "'completed' | 'pending' | 'failed' | 'cancelled' | 'refunded'", description: "Order status after the check" },
      { name: "orderId", type: "number", description: "Order id, or null" },
      { name: "message", type: "string", description: "Result or reason" },
    ],
    notes: [
      "Never reads a session. Trust comes from asking PayU directly, so an order is only completed when PayU reports success.",
      "Read orderStatus, not just success: a PayU failure returns success true with orderStatus failed, and does not change the order.",
      "Safe to repeat. Returns 404 for an unknown order, 400 when it has no transaction id, and 500 for PayU errors.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/verify-pending",
    description: "Re-check the signed-in user's stuck pending payments with PayU and settle the ones PayU has resolved",
    auth: "any",
    category: "Payments",
    usedBy: ["web"],
    responseFields: [
      { name: "verifiedCount", type: "number", description: "Pending orders checked" },
      { name: "updatedOrders", type: "array", description: "{ orderId, previousStatus: 'pending', newStatus: 'completed' | 'failed' | 'cancelled' }" },
      { name: "verifiedSubscriptionTransactionsCount", type: "number", description: "Pending teacher subscription payments checked" },
      { name: "updatedSubscriptionTransactions", type: "array", description: "{ transactionId, previousStatus: 'pending', newStatus: 'completed' | 'failed' }" },
    ],
    notes: [
      "Takes no input and only touches the caller's own records. The web runs it in the background after sign-in.",
      "Only orders pending for more than 5 minutes are checked. Sponsorship orders are skipped. Anything PayU cannot resolve is marked failed after 24 hours.",
      "Returns 401 when signed out.",
    ],
  },

  // Teacher payments
  {
    method: "POST",
    route: "/_api/payment/payu/recurring/create-mandate",
    description: "Start an autopay subscription sign-up and return the PayU form fields",
    auth: "teacher",
    category: "Teacher payments",
    usedBy: ["web"],
    bodyParams: [
      { name: "planId", type: "number", required: true, description: "Id of an active subscription plan" },
    ],
    responseFields: [
      { name: "key, txnid, amount, productinfo, firstname, email, phone, surl, furl, hash, payuUrl", type: "string", description: "PayU form fields. surl and furl are /_api/payment/payu/recurring/mandate-callback" },
      { name: "si", type: "string", description: "Always '1', marking a standing instruction" },
      { name: "si_details", type: "string", description: "JSON with billingAmount, billingCycle (MONTHLY, or YEARLY for plans over 31 days), billingInterval, paymentStartDate, paymentEndDate (5 years out) and billingCurrency INR" },
      { name: "api_version", type: "string", description: "Always '7'" },
    ],
    notes: [
      "Account owners only. Team managers get 403. Admin-role accounts pass the role check.",
      "Marks the teacher's other pending subscription payments failed, then creates a new pending one.",
      "The web posts the fields through POST /_api/payment/payu/redirect. Returns 401 when signed out and 400 for other failures.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/recurring/charge-mandate",
    description: "Charge a teacher's autopay mandate for the next subscription period when it is due",
    auth: "teacher",
    category: "Teacher payments",
    usedBy: ["web"],
    bodyParams: [
      { name: "subscriptionId", type: "number", required: true, description: "Id of the owner's active subscription" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "True when the charge was captured or is processing" },
      { name: "message", type: "string", description: "'Subscription renewed successfully.' or 'Payment is being processed.'" },
    ],
    notes: [
      "Account owners only (403 otherwise, 401 when signed out). The web calls it in the background when a renewal is due.",
      "Returns 400 when autopay mode is off, the subscription is not chargeable yet (no mandate, not due, or the pre-debit notice is under 23 hours old), or a renewal is already pending.",
      "A captured charge extends the subscription and emails the teacher. A pending one is settled later by /_api/payment/payu/verify-pending. A declined one returns 400.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/recurring/mandate-callback",
    description: "PayU result for an autopay sign-up: activate the teacher's subscription and store the mandate",
    auth: "signature",
    category: "Teacher payments",
    usedBy: ["web"],
    bodyParams: [
      { name: "status, txnid, amount, productinfo, firstname, email, key, hash", type: "string", required: true, description: "Standard PayU response fields" },
      { name: "mihpayid", type: "string", required: false, description: "PayU payment id. For a standing instruction it is the mandate id used for later charges" },
      { name: "IsStandingInstructionSet", type: "string", required: false, description: "Tells whether PayU registered the mandate" },
    ],
    responseFields: [
      { name: "(html)", type: "page", description: "A bridge page that reports to the opener window or moves the browser to /teacher/subscription" },
    ],
    notes: [
      "PayU calls it. Clients never do.",
      `${PAYU_HASH_NOTE} The browser goes to /teacher/subscription?error=invalid_hash.`,
      "Success activates the plan, replaces any active subscription and stores the mandate, then redirects with status=mandate_created (or activated_without_autopay when PayU registered no mandate).",
      "Cancel leaves the payment pending. Any other status marks it failed and emails the teacher.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/subscription/callback",
    description: "PayU result for a one-off teacher subscription payment: activate or fail the plan",
    auth: "signature",
    category: "Teacher payments",
    usedBy: ["web"],
    bodyParams: [
      { name: "status, txnid, amount, productinfo, firstname, email, key, hash", type: "string", required: true, description: "Standard PayU response fields" },
      { name: "udf1", type: "string", required: false, description: "Wallet transaction id for a split wallet and PayU payment" },
    ],
    responseFields: [
      { name: "(html)", type: "page", description: "A bridge page that reports to the opener window or moves the browser to /teacher/subscription" },
    ],
    notes: [
      "PayU calls it for payments started by the teacher subscription checkout. Clients never do.",
      `${PAYU_HASH_NOTE} The browser goes to /teacher/subscription?error=invalid_hash.`,
      "Success replaces any active subscription with the new plan and emails the teacher. Cancel or failure refunds any wallet part of a split payment.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/subscription/verify-and-complete",
    description: "Ask PayU for a subscription payment's real status and activate the plan if it was paid",
    auth: "none",
    category: "Teacher payments",
    usedBy: ["web"],
    bodyParams: [
      { name: "txnid", type: "string", required: false, description: "PayU transaction id. Send txnid or transactionId" },
      { name: "transactionId", type: "number", required: false, description: "Subscription transaction id" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "True when the check ran" },
      { name: "status", type: "'completed' | 'pending' | 'failed'", description: "Status after the check" },
      { name: "transactionId", type: "number", description: "Subscription transaction id, or null" },
      { name: "subscriptionId", type: "number", description: "Activated subscription, when known" },
      { name: "message", type: "string", description: "Result or reason" },
    ],
    notes: [
      "Never reads a session. Trust comes from asking PayU directly.",
      "Unlike the callback, it does not expire an existing active subscription or link a wallet part.",
      "Returns 404 when the transaction is not found, 400 when it has no PayU id and 500 for PayU errors.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/sponsor-callback",
    description: "PayU result for a teacher's sponsored enrollment: enroll the sponsored student",
    auth: "signature",
    category: "Teacher payments",
    usedBy: ["web"],
    bodyParams: [
      { name: "status, txnid, amount, productinfo, firstname, email, key, hash", type: "string", required: true, description: "Standard PayU response fields. txnid is sponsor-<enrollmentId>-<timestamp>" },
      { name: "unmappedstatus", type: "string", required: false, description: "'userCancelled' marks a Cancel or Back press" },
    ],
    responseFields: [
      { name: "(html)", type: "page", description: "A bridge page that reports to the opener window or moves the browser to /teacher/students" },
    ],
    notes: [
      "PayU calls it for payments started by the teacher sponsorship dialog. Clients never do.",
      `${PAYU_HASH_NOTE} The browser goes to /teacher/students?sponsored=failed&reason=invalid_hash.`,
      "Success enrolls the student in the sponsored item and emails the teacher and the student. Cancel or failure closes the order.",
    ],
  },
  {
    method: "POST",
    route: "/_api/payment/payu/subscription/initiate",
    description: "Create a pending one-off PayU payment for a teacher subscription plan",
    auth: "teacher",
    category: "Teacher payments",
    usedBy: [],
    deprecated: "Use the teacher subscription checkout (/_api/teacher/subscription/wallet-subscribe) or /_api/payment/payu/recurring/create-mandate instead. Nothing calls it any more, but it is still live and shares its callback with the current checkout.",
    bodyParams: [
      { name: "planId", type: "number", required: true, description: "Id of an active subscription plan" },
    ],
    responseFields: [
      { name: "key, txnid, amount, productinfo, firstname, email, phone, surl, furl, hash, payuUrl", type: "string", description: "PayU form fields. surl and furl are /_api/payment/payu/subscription/callback" },
    ],
    notes: ["Account owners only. Marks the teacher's other pending subscription payments failed, without refunding any wallet part."],
  },

  // Promo codes
  {
    method: "POST",
    route: "/_api/promo-codes/validate",
    description: "Check a promo code against the items being bought and preview the discount",
    auth: "any",
    category: "Promo codes",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "code", type: "string", required: true, description: "Promo code text, matched exactly. Codes are stored in capitals" },
      { name: "items", type: "array", required: false, description: "{ id, type: 'course' | 'test' | 'live_test' | 'bundle' | 'digital_product', price } for each item. Preferred format" },
      { name: "totalAmount", type: "number", required: true, description: "Total of the items. Only used to split prices in the older format" },
      { name: "itemType", type: "'course' | 'test' | 'live_test' | 'bundle' | 'digital_product'", required: false, description: "Older format: one type for all itemIds" },
      { name: "itemIds", type: "array", required: false, description: "Older format: item ids, used with itemType when items is not sent" },
    ],
    responseFields: [
      { name: "valid", type: "boolean", description: "True when the code applies to at least one item and passes its rules" },
      { name: "message", type: "string", description: "Why the code does not apply, or 'Promo code applied successfully!'" },
      { name: "discountAmount", type: "number", description: "Discount on the eligible items. Only when valid" },
      { name: "promoCodeId", type: "number", description: "Id to pass to the checkouts. Only when valid" },
      { name: "eligibleItemIds", type: "array", description: "Items the code applies to" },
      { name: "ineligibleItemIds", type: "array", description: "Items it does not apply to" },
      { name: "discountBreakdown", type: "string", description: "e.g. 'Applied to 1 out of 2 items in cart'" },
    ],
    notes: [
      "A code that does not apply is a 200 with valid false, not an error. Reasons: unknown, inactive, outside its dates, usage or per-user limit reached, no eligible items, or minimum purchase not met.",
      "An item is eligible when the code was made by that item's teacher or by an admin, covers the item's type, and lists the item if it targets specific items.",
      "This is only a preview. The checkout recalculates the discount from database prices.",
      "Validation errors return 400. A signed-out request returns 500.",
    ],
  },
  {
    method: "GET",
    route: "/_api/promo-codes/public",
    description: "List the public coupons a teacher offers on one item",
    auth: "none",
    category: "Promo codes",
    usedBy: ["web"],
    queryParams: [
      { name: "itemType", type: "'course' | 'test' | 'live_test' | 'bundle' | 'digital_product'", required: true, description: "Kind of item" },
      { name: "itemId", type: "number", required: true, description: "Item id" },
    ],
    responseFields: [
      { name: "promoCodes", type: "array", description: "At most 5, newest first: { id, code, discountType: 'percentage' | 'fixed', discountValue, minPurchaseAmount, maxDiscountAmount, validUntil }" },
    ],
    notes: [
      "Only active, current, public codes made by the item's own teacher that cover the item are listed. Admin-made codes never appear.",
      "An unknown itemId returns an empty list. Bad parameters return 400.",
    ],
  },

  // Wallet and payouts
  {
    method: "GET",
    route: "/_api/student/wallet/balance",
    description: "Get the signed-in student's prize money balance and totals",
    auth: "student",
    category: "Wallet and payouts",
    usedBy: ["web", "mobile"],
    responseFields: [
      { name: "availableBalance", type: "number", description: "Credits minus completed and pending withdrawals minus wallet purchases, never below 0" },
      { name: "totalCredits", type: "number", description: "Prize credits and prize refunds" },
      { name: "totalWithdrawn", type: "number", description: "Completed and pending withdrawals" },
      { name: "totalPurchased", type: "number", description: "Wallet purchases" },
      { name: "breakdown", type: "object", description: "{ credits, withdrawals, purchases }, each { count, amount }" },
    ],
    notes: ["Returns 403 for non-students and 401 when signed out. Failed withdrawals do not count against the balance."],
  },
  {
    method: "GET",
    route: "/_api/student/wallet/transactions",
    description: "List the student's wallet credits, purchases and withdrawals as one paged history, newest first",
    auth: "student",
    category: "Wallet and payouts",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "page", type: "number", required: false, description: "Page number, default 1" },
      { name: "limit", type: "number", required: false, description: "Page size, default 20, maximum 100" },
    ],
    responseFields: [
      { name: "transactions", type: "array", description: "{ id, studentId, transactionType: 'prize_credit' | 'prize_lock_refund' | 'purchase_debit' | 'withdrawal_debit', amount, description, referenceId, createdAt, withdrawalStatus? }" },
      { name: "total", type: "number", description: "Transactions plus withdrawals" },
      { name: "page", type: "number", description: "Page returned" },
      { name: "limit", type: "number", description: "Page size used" },
    ],
    notes: [
      "Withdrawals appear as withdrawal_debit entries with withdrawalStatus set. Ids from the two sources can repeat, so do not use id alone as a list key.",
      "Returns 403 for non-students. Other failures, including a missing session, return 400.",
    ],
  },
  {
    method: "POST",
    route: "/_api/student/wallet/purchase",
    description: "Buy everything in the student's cart with the prize money wallet",
    auth: "student",
    category: "Wallet and payouts",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "promoCodeId", type: "number", required: false, description: "Promo code id to apply, not the code text" },
    ],
    responseFields: [
      { name: "orderId", type: "number", description: "The new completed order" },
      { name: "walletBalanceAfter", type: "number", description: "Balance after the purchase" },
      { name: "amountDeducted", type: "number", description: "Amount taken from the wallet" },
    ],
    notes: [
      "Buys the whole cart. The order is created completed, the wallet is debited, enrollments are made and the cart is cleared in one transaction.",
      "Every error returns 400, including non-students, an empty cart, a bad promo code, 'Insufficient wallet balance' and a missing session.",
      "The wallet is locked during the purchase, so a parallel purchase or withdrawal cannot spend the same money.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/withdrawal/list",
    description: "List all of the student's prize money withdrawal requests, newest first",
    auth: "student",
    category: "Wallet and payouts",
    usedBy: ["web", "mobile"],
    responseFields: [
      { name: "withdrawals", type: "array", description: "{ id, studentId, amount, status: 'pending' | 'completed' | 'failed' | 'cancelled', requestedDate, processedDate, transactionId, notes, balanceAtRequest, createdAt, updatedAt }" },
    ],
    notes: [
      "Not paged and has no total field.",
      "pending waits for an admin, completed means paid (transactionId set by the admin), failed means rejected and the money is released. Nothing sets cancelled today.",
      "Returns 403 for non-students. A signed-out request returns 500.",
    ],
  },
  {
    method: "POST",
    route: "/_api/student/withdrawal/request",
    description: "Request a payout of prize money to the student's verified bank account",
    auth: "student",
    category: "Wallet and payouts",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "amount", type: "number", required: true, description: "Amount in INR, at least 50 and at most the available balance" },
      { name: "notes", type: "string", required: false, description: "Free text note stored on the request" },
    ],
    responseFields: [
      { name: "(withdrawal)", type: "object", description: "The new withdrawal row: { id, studentId, amount, status: 'pending', requestedDate, notes, processedDate, transactionId, balanceAtRequest, createdAt, updatedAt }" },
    ],
    notes: [
      "Returns 201 on success.",
      "Rules, each a 400: minimum INR 50, bank details must be verified, only one pending request at a time, and the amount cannot exceed the available balance.",
      "Returns 403 for non-students. Other failures, including a missing session, return 400.",
      "Notifies the admins and emails the student a confirmation.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/bank-details",
    description: "Get the signed-in student's saved payout bank details and verification status",
    auth: "student",
    category: "Wallet and payouts",
    usedBy: ["web", "mobile"],
    responseFields: [
      { name: "(bank details)", type: "object", description: "The saved row itself, or null: { id, studentId, bankAccountHolderName, bankAccountNumber, bankIfscCode, bankName, upiId, panNumber, panCardImageBase64, verificationStatus: 'pending' | 'verified' | 'rejected', rejectionReason, createdAt, updatedAt }" },
    ],
    notes: [
      "Not wrapped in a bankDetails field.",
      "The owner gets their account number, IFSC, PAN and UPI id in full, so keep the response out of logs and shared caches.",
      "Despite its name, panCardImageBase64 is a signed link to the PAN image that expires after 10 minutes.",
      "Returns 403 for non-students. A signed-out request returns 500.",
    ],
  },
  {
    method: "POST",
    route: "/_api/student/bank-details/add",
    description: "Save or replace the student's payout bank details and PAN, and send them for verification",
    auth: "student",
    category: "Wallet and payouts",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "bankAccountHolderName", type: "string", required: true, description: "At least 2 characters" },
      { name: "bankAccountNumber", type: "string", required: true, description: "At least 5 characters" },
      { name: "bankIfscCode", type: "string", required: true, description: "Capitals matching ^[A-Z]{4}0[A-Z0-9]{6}$, e.g. SBIN0001234" },
      { name: "bankName", type: "string", required: true, description: "At least 2 characters" },
      { name: "panNumber", type: "string", required: true, description: "Capitals matching ^[A-Z]{5}[0-9]{4}[A-Z]{1}$, e.g. ABCDE1234F" },
      { name: "panCardImageBase64", type: "string", required: true, description: "A data:image/<type>;base64,... URI of at most 5 MB, or a link to an image already uploaded to this student's private upload folder" },
      { name: "upiId", type: "string", required: false, description: "Matching ^[\\w.-]+@[\\w.-]+$, e.g. name@bank. May be empty" },
    ],
    responseFields: [
      { name: "(bank details)", type: "object", description: "The saved row, same shape as GET /_api/student/bank-details, with verificationStatus 'pending'" },
    ],
    notes: [
      "Saving always resets verification to pending and clears any rejection reason, so the details must be verified again before the next withdrawal.",
      "The student needs at least INR 50 of available prize money first (400 otherwise).",
      "The mobile app sends a data URI. The web uploads the image first and sends its link.",
      "Returns 403 for non-students. Validation errors and a missing session return 400. Admins are notified to review the details.",
    ],
  },
  {
    method: "GET",
    route: "/_api/ifsc-lookup",
    description: "Look up a bank branch from an IFSC code",
    auth: "any",
    category: "Wallet and payouts",
    usedBy: ["web"],
    queryParams: [
      { name: "ifsc", type: "string", required: true, description: "IFSC code. Trimmed and uppercased, then must match ^[A-Z]{4}0[A-Z0-9]{6}$" },
    ],
    responseFields: [
      { name: "ifsc", type: "string", description: "The IFSC code" },
      { name: "bank", type: "string", description: "Bank name" },
      { name: "branch", type: "string", description: "Branch name, or null" },
      { name: "city", type: "string", description: "City, or null" },
      { name: "state", type: "string", description: "State, or null" },
    ],
    notes: [
      "Requires sign-in so it is not an open proxy. Data comes from Razorpay's public IFSC directory.",
      "Errors are { error, notFound }: 400 for a malformed code, 404 when no branch exists, 502 when the directory cannot be reached.",
      "The mobile app checks the IFSC format locally and does not call it.",
    ],
  },
];
