import { ApiEndpoint } from "./apiDocsTypes";

export const apiDocsContent: ApiEndpoint[] = [
  // Courses
  {
    method: "GET",
    route: "/_api/courses/list",
    description: "List published courses with filters, sorting and paging",
    auth: "none",
    category: "Courses",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "search", type: "string", required: false, description: "Case-insensitive match on title and description" },
      { name: "category", type: "string", required: false, description: "Exact category name" },
      { name: "level", type: "'beginner' | 'intermediate' | 'advanced'", required: false, description: "Course level. Not validated" },
      { name: "language", type: "string", required: false, description: "Comma-separated languages. A course matches if its language equals any of them" },
      { name: "priceType", type: "'free' | 'paid' | 'all'", required: false, description: "'free' returns price 0, 'paid' returns price above 0. Omitted or 'all' applies no price filter" },
      { name: "minPrice", type: "number", required: false, description: "Minimum effective (discounted) price. Only applied when priceType is 'paid'" },
      { name: "maxPrice", type: "number", required: false, description: "Maximum effective (discounted) price. Only applied when priceType is 'paid'" },
      { name: "sortBy", type: "'newest' | 'price_asc' | 'price_desc' | 'popular'", required: false, description: "Default 'newest'. Unknown values fall back to 'newest'" },
      { name: "examId", type: "number", required: false, description: "Only courses listed under this exam, as primary or additional exam" },
      { name: "page", type: "number", required: false, description: "Page number, default 1" },
      { name: "limit", type: "number", required: false, description: "Items per page, default 6, no maximum" },
    ],
    responseFields: [
      { name: "courses", type: "array", description: "Array of { id, slug, title, description, thumbnailUrl, thumbnailImageUrl, introVideoUrl, price, discountPrice, category, level, language, status, publishedAt, views, examId, examName, teacherName, teacherSlug, teacherIsVerified, teacherAvatarUrl, teacherTagline, teacherYearsOfExperience, enrollmentCount, avgRating, ratingsCount }" },
      { name: "categories", type: "array", description: "Distinct non-empty category names across all published courses, ignoring the current filters" },
      { name: "pagination", type: "object", description: "{ page, limit, totalCount, totalPages }" },
    ],
    notes: [
      "Under the 'newest' and 'popular' sorts, courses from the pinned teacher list come first.",
      "Query values are not validated, so a non-numeric or negative page or limit returns 500.",
    ],
  },
  {
    method: "GET",
    route: "/_api/courses/details",
    description: "Get a published course with its curriculum, teacher, reviews and the caller's enrollment state",
    auth: "optional",
    category: "Courses",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "slug", type: "string", required: true, description: "Course slug" },
    ],
    responseFields: [
      { name: "(course fields)", type: "object", description: "The course sits at the top level, with no wrapper: id, slug, title, description, price, discountPrice, thumbnailUrl, thumbnailImageUrl, introVideoUrl, category, level, language, status, estimatedDurationMinutes, examId, examName, publishedAt, rating, reviewsCount, views" },
      { name: "teacher", type: "object", description: "{ id, displayName, profilePicture, isVerified, slug, bio, academyName }" },
      { name: "sections", type: "array", description: "Ordered { id, courseId, title, description, orderIndex, lessons }, where lessons are { id, sectionId, title, description, contentType, durationMinutes, isPreview, orderIndex, contentUrl?, textContent? }" },
      { name: "reviews", type: "array", description: "Newest first: { id, rating, reviewText, createdAt, userId, reviewerName, reviewerAvatarUrl }" },
      { name: "isEnrolled", type: "boolean", description: "True when the signed-in user is enrolled. False when signed out" },
      { name: "disclaimer", type: "string", description: "Standard product disclaimer" },
      { name: "seo", type: "object", description: "{ indexable, qualityScore, robots }" },
    ],
    notes: [
      "Returns 400 when slug is missing and 404 for an unknown or unpublished course.",
      "contentUrl and textContent are only included for preview lessons.",
      "Bearer-only behaviour: without an Authorization bearer header (the web), a preview PDF lesson has contentUrl null, and the web reads it through /_api/reader/info and /_api/reader/page with type=lessonPreview. Bearer requests (the mobile app) get the PDF link.",
      "Each call increments the course view counter.",
    ],
  },
  {
    method: "GET",
    route: "/_api/courses/related",
    description: "List published courses related to a given course",
    auth: "none",
    category: "Courses",
    usedBy: ["web"],
    queryParams: [
      { name: "courseId", type: "number", required: true, description: "Id of the course to find related courses for" },
      { name: "limit", type: "number", required: false, description: "1 to 10, default 4" },
    ],
    responseFields: [
      { name: "courses", type: "array", description: "Same item shape as /_api/courses/list" },
    ],
    notes: [
      "Returns 404 when courseId does not exist. Invalid values return 500, not 400.",
      "Filled in three tiers: same teacher and category, then same exam, then everything else by rating. The course itself and unpublished courses are left out.",
    ],
  },
  {
    method: "POST",
    route: "/_api/courses/enroll-free",
    description: "Enroll the signed-in user in a free course",
    auth: "any",
    category: "Courses",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "courseId", type: "number", required: true, description: "Id of a published course whose list price is 0" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "Always true on success" },
      { name: "enrollmentId", type: "number", description: "Id of the new enrollment" },
    ],
    notes: [
      "Teachers get 403. No other role is checked, so admin-role accounts are not blocked.",
      "Returns 404 for an unknown or unpublished course, and 400 when the course is not free (a discounted price does not count) or the user is already enrolled.",
      "Emails the student and the teacher. A signed-out call returns 500 with details 'Not authenticated'.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/enrolled-courses",
    description: "List the courses the signed-in user is enrolled in, with progress and review state",
    auth: "any",
    category: "Courses",
    usedBy: ["web", "mobile"],
    responseFields: [
      { name: "enrolledCourses", type: "array", description: "Most recently accessed first: { id, title, thumbnailUrl, thumbnailImageUrl, introVideoUrl, category, teacherName, enrolledAt, completionPercentage, lastAccessedAt, totalLessons, hasReviewed, reviewRating, reviewText }" },
    ],
    notes: [
      "Takes no parameters and is not paged. The limit the mobile app sends is ignored.",
      "A signed-out call returns 500 with details 'Not authenticated'.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/course/lessons",
    description: "Get a course and its full section and lesson list for an enrolled user",
    auth: "any",
    category: "Courses",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "courseId", type: "number", required: true, description: "Id of a course the caller is enrolled in" },
    ],
    responseFields: [
      { name: "course", type: "object", description: "The course row, with price as a number" },
      { name: "sections", type: "array", description: "Ordered { id, courseId, title, description, orderIndex, lessons }, where lessons are full lesson rows: { id, sectionId, title, description, contentType, contentUrl, contentFileId, textContent, durationMinutes, isPreview, orderIndex, plus video processing fields }" },
    ],
    notes: [
      "Returns 400 for a bad courseId and 403 'Not enrolled in this course' without an enrollment. There is no role check.",
      "Updates the enrollment's last-accessed time on every call.",
      "Bearer-only behaviour: without an Authorization bearer header (the web), PDF lessons have contentUrl and contentFileId set to null and open through /_api/reader/info and /_api/reader/page with type=lesson. Bearer requests (the mobile app) get the PDF link.",
      "Progress is not included. Use /_api/student/course/progress.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/course/progress",
    description: "Get the signed-in user's lesson progress for an enrolled course",
    auth: "any",
    category: "Courses",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "courseId", type: "number", required: true, description: "Id of a course the caller is enrolled in" },
    ],
    responseFields: [
      { name: "enrollmentId", type: "number", description: "The caller's enrollment" },
      { name: "completionPercentage", type: "number", description: "0 to 100" },
      { name: "completedLessonIds", type: "array", description: "Ids of lessons marked complete" },
    ],
    notes: ["Returns 400 for a bad courseId and 403 without an enrollment."],
  },
  {
    method: "POST",
    route: "/_api/student/course/mark-complete",
    description: "Mark a lesson complete and recalculate course completion",
    auth: "any",
    category: "Courses",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "lessonId", type: "number", required: true, description: "Id of a lesson in a course the caller is enrolled in" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "Always true on success" },
      { name: "progress", type: "object", description: "The new { id, enrollmentId, lessonId, completedAt } row. Absent when the lesson was already complete" },
      { name: "completionPercentage", type: "number", description: "Updated completion, rounded, 0 to 100" },
    ],
    notes: [
      "Returns 404 for an unknown lesson and 403 without an enrollment. There is no role check.",
      "Safe to repeat.",
    ],
  },
  {
    method: "POST",
    route: "/_api/student/course/mark-incomplete",
    description: "Remove a lesson's completion mark and recalculate course completion",
    auth: "student",
    category: "Courses",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "lessonId", type: "number", required: true, description: "Id of a lesson in a course the caller is enrolled in" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "Always true on success" },
      { name: "completionPercentage", type: "number", description: "Updated completion, rounded, 0 to 100" },
    ],
    notes: [
      "Non-students get 403. Returns 404 for an unknown lesson and 403 without an enrollment.",
      "Safe to repeat.",
    ],
  },
  {
    method: "POST",
    route: "/_api/student/course/signed-video-url",
    description: "Get the playback URL and player type for a course video lesson",
    auth: "student",
    category: "Courses",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "courseId", type: "number", required: true, description: "Id of the course the lesson belongs to" },
      { name: "lessonId", type: "number", required: true, description: "Id of the video lesson" },
      { name: "videoUrl", type: "string", required: true, description: "The lesson's stored contentUrl. Must match exactly" },
    ],
    responseFields: [
      { name: "signedUrl", type: "string", description: "A 30-minute signed storage URL for 'r2', the stored URL for 'youtube', or the embed URL for 'gumlet' (empty while Gumlet is still processing)" },
      { name: "expiresIn", type: "number", description: "Seconds until signedUrl expires: 1800 for 'r2', 0 for 'youtube' and 'gumlet'" },
      { name: "player", type: "'r2' | 'youtube' | 'gumlet'", description: "Which player the client should use" },
      { name: "gumletState", type: "'ready' | 'processing'", description: "Only for 'gumlet'. 'processing' means check again later" },
    ],
    notes: [
      "Students and admin-role accounts are allowed. Admins skip the enrollment check. Other roles get 403.",
      "Returns 401 when signed out, 404 for an unknown lesson, 400 when the lesson is not in the course or videoUrl does not match, and 403 without an enrollment.",
      "YouTube lessons skip the enrollment check. A lesson with a ready Gumlet DRM copy is only ever played through the Gumlet embed.",
    ],
  },
  {
    method: "POST",
    route: "/_api/courses/purchase",
    description: "Start a PayU payment for a single paid course",
    auth: "any",
    category: "Courses",
    usedBy: [],
    deprecated: "Use /_api/cart/add, then /_api/payment/payu/redirect (web) or /_api/payment/payu/initiate (mobile app), instead. Nothing calls it, and the PayU callback never completes the course transaction it creates, so a payment made through it is not fulfilled.",
    bodyParams: [
      { name: "courseId", type: "number", required: true, description: "Id of a published course priced above 0" },
    ],
    responseFields: [
      { name: "key, txnid, amount, productinfo, firstname, email, phone, surl, furl, hash, payuUrl", type: "string", description: "PayU form fields. txnid is 'testkart-course-<random>'" },
    ],
    notes: ["Every failure returns 500 'Failed to initiate payment' with the reason in details."],
  },

  // Bundles
  {
    method: "GET",
    route: "/_api/bundles/list",
    description: "List published bundles with filters, sorting and paging",
    auth: "none",
    category: "Bundles",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "page", type: "number", required: false, description: "Page number, default 1" },
      { name: "limit", type: "number", required: false, description: "Items per page, default 10, no maximum" },
      { name: "sort", type: "'newest' | 'popular' | 'price_asc' | 'price_desc'", required: false, description: "Default 'newest'" },
      { name: "teacherId", type: "number", required: false, description: "Only bundles by this teacher" },
      { name: "minPrice", type: "number", required: false, description: "Minimum bundle price" },
      { name: "maxPrice", type: "number", required: false, description: "Maximum bundle price" },
      { name: "search", type: "string", required: false, description: "Case-insensitive match on title and description" },
      { name: "examId", type: "number", required: false, description: "Only bundles with at least one item listed under this exam" },
    ],
    responseFields: [
      { name: "bundles", type: "array", description: "Array of { id, slug, title, description, thumbnailUrl, introVideoUrl, price, originalPrice, discountPercentage, isPublished, publishedAt, createdAt, updatedAt, teacherId, teacherName, teacherIsVerified, teacherAvatarUrl, itemCount, courseTitles }" },
      { name: "total", type: "number", description: "Bundles matching the filters" },
      { name: "page", type: "number", description: "Page used" },
      { name: "limit", type: "number", description: "Page size used" },
    ],
    notes: ["Invalid query values return 400 'Invalid query parameters'. courseTitles lists only the course items, while itemCount counts every item type."],
  },
  {
    method: "GET",
    route: "/_api/bundles/details",
    description: "Get a published bundle with its items, teacher and the caller's enrollment state",
    auth: "optional",
    category: "Bundles",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "slug", type: "string", required: true, description: "Bundle slug" },
    ],
    responseFields: [
      { name: "(bundle fields)", type: "object", description: "The bundle sits at the top level, with no wrapper: id, slug, title, description, price, originalPrice, discountPercentage, thumbnailUrl, introVideoUrl, isPublished, publishedAt" },
      { name: "teacher", type: "object", description: "{ id, displayName, profilePicture }" },
      { name: "items", type: "array", description: "By orderIndex: { type: 'course' | 'test' | 'digital_product', id, title, slug, description, thumbnailUrl, price, orderIndex }, plus level and language for courses, durationMinutes, totalQuestions and language for tests, language and pageCount for study notes" },
      { name: "isEnrolled", type: "boolean", description: "True when the signed-in user is enrolled in the bundle" },
      { name: "disclaimer", type: "string", description: "Standard product disclaimer" },
      { name: "seo", type: "object", description: "{ indexable, qualityScore, robots }" },
    ],
    notes: [
      "Returns 400 when slug is missing and 404 for an unknown or unpublished bundle.",
      "items lists every attached item, whether or not the item itself is published.",
    ],
  },
  {
    method: "POST",
    route: "/_api/bundles/purchase",
    description: "Enroll in a free bundle, or start a PayU payment for a paid bundle without a promo code",
    auth: "any",
    category: "Bundles",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "bundleId", type: "number", required: true, description: "Id of a published bundle" },
      { name: "promoCode", type: "string", required: false, description: "Accepted but ignored. Promo codes on bundles go through GET /_api/payment/payu/bundle-redirect" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "Always true on success" },
      { name: "isFree", type: "boolean", description: "True when the bundle costs 0 and the enrollment is already done" },
      { name: "paymentData", type: "object", description: "Only when isFree is false: PayU form fields { key, txnid, amount, productinfo, firstname, email, phone, surl, furl, hash, payuUrl }" },
    ],
    notes: [
      "Returns 404 for an unknown or unpublished bundle and 409 when the user is already enrolled.",
      "Free bundle: creates a completed zero-amount order and the bundle enrollment, then emails the student and the teacher. It does not unlock the individual items the way the PayU callback does for paid bundles, so the items can stay locked.",
      "Paid bundle: creates a pending order and returns the PayU fields. /_api/payment/payu/callback completes the order and unlocks the items.",
      "The web only calls it for free bundles and sends paid ones to /_api/payment/payu/bundle-redirect. No role check, so teachers are not blocked.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/bundles/enrolled",
    description: "List the bundles the signed-in user is enrolled in, with per-item access state",
    auth: "any",
    category: "Bundles",
    usedBy: ["mobile"],
    responseFields: [
      { name: "enrolledBundles", type: "array", description: "Newest first: { id, title, slug, thumbnailUrl, teacherName, enrolledAt, courses: [{ id, title, slug, completionPercentage?, lastAccessedAt? }], mockTests: [{ id, title, slug, isEnrolled }], digitalProducts: [{ id, title, slug, isPurchased }] }" },
    ],
    notes: [
      "Takes no parameters and is not paged.",
      "isEnrolled and isPurchased show whether the user really has each item, so items a free bundle did not unlock show false. The mobile app uses this to warn the student.",
    ],
  },

  // Study notes
  {
    method: "GET",
    route: "/_api/shop/list",
    description: "List published study notes with filters, sorting and paging",
    auth: "none",
    category: "Study notes",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "category", type: "string", required: false, description: "Exact category name" },
      { name: "priceMin", type: "number", required: false, description: "Minimum price" },
      { name: "priceMax", type: "number", required: false, description: "Maximum price" },
      { name: "language", type: "string", required: false, description: "Exact language" },
      { name: "search", type: "string", required: false, description: "Case-insensitive match on title and description" },
      { name: "sort", type: "'newest' | 'popular' | 'price_asc' | 'price_desc'", required: false, description: "Default 'newest'" },
      { name: "examId", type: "number", required: false, description: "Only study notes listed under this exam" },
      { name: "page", type: "number", required: false, description: "Page number, default 1" },
      { name: "limit", type: "number", required: false, description: "1 to 100, default 20" },
    ],
    responseFields: [
      { name: "products", type: "array", description: "Array of { id, title, slug, price, thumbnailUrl, category, publishedAt, pageCount, rating, ratingsCount, examName, totalPurchases, views, teacherName, teacherAvatar, teacherIsVerified, teacherSlug, teacherTagline, teacherYearsOfExperience, fileCount }" },
      { name: "page", type: "number", description: "Page used" },
      { name: "limit", type: "number", description: "Page size used" },
      { name: "totalCount", type: "number", description: "Matching study notes" },
      { name: "totalPages", type: "number", description: "Number of pages" },
    ],
    notes: [
      "Invalid values return 500 'Failed to list products', not 400.",
      "Under the 'newest' and 'popular' sorts, study notes from the pinned teacher list come first.",
    ],
  },
  {
    method: "GET",
    route: "/_api/shop/details",
    description: "Get a published study note with its file list, teacher and reviews",
    auth: "optional",
    category: "Study notes",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "slug", type: "string", required: true, description: "Study note slug" },
    ],
    responseFields: [
      { name: "product", type: "object", description: "{ id, title, slug, description, shortDescription, price, thumbnailUrl, previewUrl, previewPages, pageCount, fileSizeBytes, language, category, tags, examName, examId, rating, reviewsCount, totalPurchases, views, fileCount, files: [{ id, title, pageCount, fileSizeBytes, orderIndex }], isPurchased, publishedAt, teacherId, teacherName, teacherSlug, teacherAvatar, teacherBio, teacherVerified, teacherAcademyName, disclaimer, seo }" },
      { name: "reviews", type: "array", description: "Newest first: { id, reviewerName, rating, reviewText, createdAt, userId }" },
    ],
    notes: [
      "isPurchased is inside product. It is false when signed out.",
      "Returns 400 when slug is missing and 404 for an unknown or unpublished study note.",
      "No file location is ever returned and previewUrl is always null. Previews come from /_api/reader on the web and /_api/shop/preview-page in the mobile app.",
      "Each call increments the view counter. A legacy single-file note gets one entry in files with id 0.",
    ],
  },
  {
    method: "GET",
    route: "/_api/shop/related",
    description: "List published study notes related to a given study note",
    auth: "none",
    category: "Study notes",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "productId", type: "number", required: true, description: "Id of the study note to find related items for" },
      { name: "limit", type: "number", required: false, description: "1 to 10, default 4" },
    ],
    responseFields: [
      { name: "products", type: "array", description: "Same item shape as /_api/shop/list" },
    ],
    notes: ["Returns 404 when productId does not exist. Invalid values return 500, not 400."],
  },
  {
    method: "POST",
    route: "/_api/shop/enroll-free",
    description: "Claim a free study note for the signed-in user",
    auth: "any",
    category: "Study notes",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "digitalProductId", type: "number", required: true, description: "Id of a published study note priced 0" },
    ],
    responseFields: [
      { name: "orderId", type: "number", description: "Id of the zero-amount completed order" },
      { name: "message", type: "string", description: "Fixed confirmation text" },
    ],
    notes: [
      "Teachers get 403. No other role is checked.",
      "Returns 404 for an unknown or unpublished note, and 400 when it is not free or already claimed.",
      "Emails the student and the teacher. A signed-out call returns 500 with details 'Not authenticated'.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/shop/purchases",
    description: "List the study notes the signed-in user has bought or claimed",
    auth: "any",
    category: "Study notes",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "page", type: "number", required: false, description: "Page number, default 1" },
      { name: "limit", type: "number", required: false, description: "Items per page, default 20, no maximum" },
    ],
    responseFields: [
      { name: "purchases", type: "array", description: "Newest first: { purchaseId, purchasedAt, downloadCount, lastDownloadedAt, productId, title, slug, thumbnailUrl, category, teacherName, fileCount, hasReviewed, reviewRating, reviewText }" },
      { name: "page", type: "number", description: "Page used" },
      { name: "limit", type: "number", description: "Page size used" },
    ],
    notes: [
      "There is no total count. Page until a short page comes back.",
      "downloadCount and lastDownloadedAt also move when the web reader opens a note.",
      "A signed-out call returns 500 with details 'Not authenticated'.",
    ],
  },
  {
    method: "GET",
    route: "/_api/student/shop/files",
    description: "List the files of a study note the signed-in user owns",
    auth: "any",
    category: "Study notes",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "productId", type: "number", required: true, description: "Id of an owned study note" },
    ],
    responseFields: [
      { name: "files", type: "array", description: "By orderIndex: { id, title, fileSizeBytes, pageCount, orderIndex }. No storage links" },
    ],
    notes: [
      "Returns 403 when the caller has not bought the note and 400 for a bad productId.",
      "A legacy single-file note returns an empty list.",
    ],
  },
  {
    method: "GET",
    route: "/_api/reader/info",
    description: "Open a study note or lesson PDF in the page reader and get its page count",
    auth: "optional",
    category: "Study notes",
    usedBy: ["web"],
    queryParams: [
      { name: "type", type: "'note' | 'notePreview' | 'lesson' | 'lessonPreview'", required: true, description: "'note' is an owned study note, 'notePreview' a study note's public preview pages, 'lesson' a PDF lesson of an enrolled course, 'lessonPreview' a free preview PDF lesson" },
      { name: "productId", type: "number", required: false, description: "Required for 'note' and 'notePreview'" },
      { name: "fileId", type: "number", required: false, description: "One file of a multi-file study note. The main file when omitted" },
      { name: "courseId", type: "number", required: false, description: "Required for 'lesson' and 'lessonPreview'" },
      { name: "lessonId", type: "number", required: false, description: "Required for 'lesson' and 'lessonPreview'" },
    ],
    responseFields: [
      { name: "title", type: "string", description: "Document title" },
      { name: "totalPages", type: "number", description: "Pages this viewer may open: the whole document, or only the preview pages" },
      { name: "firstPage", type: "object", description: "{ width, height } of page 1 in pixels" },
    ],
    notes: [
      "The preview types work signed out. 'note' and 'lesson' return 401 'Sign in to open this document.' without a session.",
      "'note' needs a purchase and 'lesson' needs an enrolled student or an admin-role user (403 otherwise). The lesson must be a PDF with a stored file (404 otherwise).",
      "Returns 400 for bad parameters and 422 when the document cannot be displayed.",
      "The file location never leaves the server. Responses are private, no-store. Pages come from /_api/reader/page.",
    ],
  },
  {
    method: "GET",
    route: "/_api/reader/page",
    description: "Get one page of a study note or lesson PDF as a watermarked image",
    auth: "optional",
    category: "Study notes",
    usedBy: ["web"],
    queryParams: [
      { name: "type", type: "'note' | 'notePreview' | 'lesson' | 'lessonPreview'", required: true, description: "Same meaning as on /_api/reader/info" },
      { name: "productId", type: "number", required: false, description: "Required for 'note' and 'notePreview'" },
      { name: "fileId", type: "number", required: false, description: "One file of a multi-file study note" },
      { name: "courseId", type: "number", required: false, description: "Required for 'lesson' and 'lessonPreview'" },
      { name: "lessonId", type: "number", required: false, description: "Required for 'lesson' and 'lessonPreview'" },
      { name: "page", type: "number", required: true, description: "Page number, 1 or more" },
    ],
    responseFields: [
      { name: "(image)", type: "image/webp", description: "The page as a WebP image, not JSON" },
    ],
    notes: [
      "Same access rules and errors as /_api/reader/info. A page past a preview's limit returns 404.",
      "Rate limited: signed-in users 120 pages a minute and 3000 a day, signed-out viewers 60 a minute and 600 a day per IP. Over the limit returns 429.",
      "Signed-in viewers get a watermark with their own name, email and mobile number. Previews get a preview watermark. Every served page is logged.",
      "Sent with Cache-Control private, max-age=1800. Errors are JSON { error }.",
    ],
  },
  {
    method: "POST",
    route: "/_api/student/shop/download",
    description: "Get a time-limited download link for a file of an owned study note",
    auth: "any",
    category: "Study notes",
    usedBy: ["mobile"],
    bodyParams: [
      { name: "productId", type: "number", required: true, description: "Id of an owned study note" },
      { name: "fileId", type: "number", required: false, description: "One file of the note. The main file when omitted" },
    ],
    responseFields: [
      { name: "downloadUrl", type: "string", description: "Signed storage URL valid for one hour" },
      { name: "expiresAt", type: "string", description: "ISO 8601 time when downloadUrl expires" },
    ],
    notes: [
      "Bearer requests only. Without an Authorization bearer header (the web, or any cookie session) it returns 403 'Study notes open in the reader. Downloads are available in the Testkart app.' The web reads notes through /_api/reader/info and /_api/reader/page.",
      "Returns 403 when the caller has not bought the note, and 404 when fileId is not part of it or no file is stored.",
      "Increments downloadCount and sets lastDownloadedAt on the purchase.",
    ],
  },
  {
    method: "GET",
    route: "/_api/shop/preview-page",
    description: "Get one rendered preview page image of a published study note",
    auth: "none",
    category: "Study notes",
    usedBy: ["mobile"],
    deprecated: "Use /_api/reader/info and /_api/reader/page with type=notePreview instead. The web has moved to those watermarked pages, and only the shipped mobile app still calls this route.",
    queryParams: [
      { name: "productId", type: "number", required: true, description: "Id of a published study note" },
      { name: "fileId", type: "number", required: false, description: "One file of a multi-file note. The main file when omitted" },
      { name: "page", type: "number", required: false, description: "Page within the preview, default 1" },
    ],
    responseFields: [
      { name: "page", type: "number", description: "Page returned" },
      { name: "totalPages", type: "number", description: "Preview pages, capped at the file's real page count" },
      { name: "imageUrl", type: "string", description: "Public CDN URL of the rendered page image" },
      { name: "width", type: "number", description: "Image width in pixels" },
      { name: "height", type: "number", description: "Image height in pixels" },
    ],
    notes: [
      "Only pages up to the note's previewPages are served, as images. The image is not watermarked.",
      "Returns 400 for bad parameters, 404 for an unknown note or file or a page past the preview, and 422 when the file cannot be rendered.",
      "The first request for a page renders it, so it can take a few seconds.",
    ],
  },
  {
    method: "GET",
    route: "/_api/files/pdf-proxy",
    description: "Stream a PDF from Testkart storage through the site's own origin for the in-browser viewer",
    auth: "none",
    category: "Study notes",
    usedBy: ["web"],
    queryParams: [
      { name: "url", type: "string", required: true, description: "Absolute URL of the file on the Testkart CDN host or the Testkart storage host" },
    ],
    responseFields: [
      { name: "(file)", type: "application/pdf", description: "The file bytes, streamed. Range requests work" },
    ],
    notes: [
      "Used by the teacher and admin PDF previews, because the storage hosts send no CORS headers. Students read documents through /_api/reader instead.",
      "No sign-in is required. The only restriction is the host allow-list.",
      "Errors are plain text, not JSON: 400 for a missing or disallowed url, 404 when the file is missing, 502 for other storage failures.",
    ],
  },

  // Reviews
  {
    method: "GET",
    route: "/_api/reviews/list",
    description: "List the reviews of a mock test series",
    auth: "none",
    category: "Reviews",
    usedBy: ["web"],
    queryParams: [
      { name: "mockTestId", type: "number", required: true, description: "Id of the mock test series" },
    ],
    responseFields: [
      { name: "reviews", type: "array", description: "Newest first: { id, rating, reviewText, createdAt, testItemId, reviewerName, reviewerAvatarUrl, testItemTitle }" },
    ],
    notes: [
      "Mock test reviews only. Course reviews come inside /_api/courses/details and study note reviews inside /_api/shop/details.",
      "Returns 400 for a missing or bad mockTestId. Not paged, and no average or total.",
    ],
  },
  {
    method: "POST",
    route: "/_api/reviews/submit",
    description: "Create or update the signed-in student's review of a mock test series, study note or course",
    auth: "student",
    category: "Reviews",
    usedBy: ["web", "mobile"],
    bodyParams: [
      { name: "mockTestId", type: "number", required: false, description: "Series to review. Send exactly one of mockTestId, digitalProductId or courseId" },
      { name: "digitalProductId", type: "number", required: false, description: "Study note to review" },
      { name: "courseId", type: "number", required: false, description: "Course to review" },
      { name: "rating", type: "number", required: true, description: "Whole number from 1 to 5" },
      { name: "reviewText", type: "string", required: false, description: "At most 1000 characters" },
    ],
    responseFields: [
      { name: "success", type: "boolean", description: "Always true on success" },
      { name: "message", type: "string", description: "'Review submitted successfully.' or 'Review updated successfully.'" },
    ],
    notes: [
      "Returns 401 when signed out and 403 for non-students.",
      "A mock test needs at least one completed attempt, a study note needs a purchase or free claim, and a course needs an enrollment of any kind (403 otherwise).",
      "One review per student per item. Sending again updates it.",
      "Returns 400 'Invalid input provided.' when not exactly one id is sent, or the rating or text is out of range.",
      "Recalculates the item's average rating. The first review of an item emails the teacher.",
    ],
  },

  // Teachers
  {
    method: "GET",
    route: "/_api/teachers/profile",
    description: "Get a teacher's public profile with their published courses, tests, live tests, study notes and bundles",
    auth: "optional",
    category: "Teachers",
    usedBy: ["web", "mobile"],
    queryParams: [
      { name: "teacherSlug", type: "string", required: true, description: "The teacher's profile slug" },
    ],
    responseFields: [
      { name: "teacher", type: "object", description: "{ id, displayName, slug, avatarUrl, bio, websiteUrl, socialLinks, awardsCertificates, languages, location, expertiseAreas, responseTime, tagline, isVerified, workExperiences, academyName, yearsOfExperience, joinedAt }" },
      { name: "courses", type: "array", description: "Published courses, same item shape as /_api/courses/list" },
      { name: "tests", type: "array", description: "Published mock test series that are not live tests, with isEnrolled" },
      { name: "liveTests", type: "array", description: "Published live tests with schedule, seats and prizes, with isEnrolled and hasAttempted" },
      { name: "products", type: "array", description: "Published study notes, same item shape as /_api/shop/list plus language" },
      { name: "bundles", type: "array", description: "{ id, slug, title, thumbnailUrl, price, originalPrice, itemCount }" },
      { name: "examNames", type: "array", description: "Every exam the teacher's published items are listed under" },
    ],
    notes: [
      "Returns 400 when teacherSlug is missing and 404 when no active teacher has that slug.",
      "With a session, isEnrolled and hasAttempted are filled in. Signed-out callers get false.",
      "The teacher's mobile number, public email and public phone are not returned.",
    ],
  },
  {
    method: "GET",
    route: "/_api/teachers/avatars",
    description: "Get names and avatars of a random sample of active teachers",
    auth: "none",
    category: "Teachers",
    usedBy: ["web"],
    responseFields: [
      { name: "teachers", type: "array", description: "Up to 50 random { displayName, avatarUrl } entries for active teachers with an avatar" },
    ],
    notes: ["Takes no parameters. Sent with Cache-Control public, max-age=300, stale-while-revalidate=600."],
  },
];
