import { ApiEndpoint } from "./apiDocsTypes";

const LEGACY_OAUTH =
  "Kept so AI connections added before 21-09-2026 keep refreshing. New clients discover the shared endpoint from /.well-known/oauth-authorization-server.";

export const apiDocsMcp: ApiEndpoint[] = [
  {
    method: "POST",
    route: "/_api/mcp/admin",
    description: "Admin MCP connector for AI assistants such as Claude, ChatGPT and Codex",
    auth: "oauth",
    category: "MCP connectors",
    usedBy: [],
    bodyParams: [
      { name: "jsonrpc", type: "'2.0'", required: true, description: "JSON-RPC version" },
      { name: "id", type: "string", required: false, description: "Request id, a string or number. Omit it for notifications" },
      { name: "method", type: "string", required: true, description: "initialize, notifications/initialized, notifications/cancelled, ping, tools/list or tools/call" },
      { name: "params", type: "object", required: false, description: "Method parameters. For tools/call: { name, arguments }" },
    ],
    responseFields: [
      { name: "jsonrpc", type: "'2.0'", description: "JSON-RPC version" },
      { name: "id", type: "string", description: "The request id" },
      { name: "result", type: "object", description: "Method result, e.g. { tools } for tools/list or the tool output for tools/call" },
    ],
    notes: [
      "Plain JSON-RPC 2.0 over the MCP Streamable HTTP transport, not superjson. Protocol versions 2025-06-18 (default), 2025-03-26 and 2024-11-05.",
      "Send Authorization: Bearer <access_token> from the MCP OAuth flow. A missing or expired token gets 401 with a WWW-Authenticate header pointing at /.well-known/oauth-protected-resource/_api/mcp/admin.",
      "The tool list follows the admin's section access: testkart_whoami, testkart_read and content tools (blog, news, careers, exam content and content_edit). Orders, payouts, users and settings are read-only.",
      "Tools that permanently delete a record refuse until the call is repeated with confirm: true.",
    ],
  },
  {
    method: "GET",
    route: "/_api/mcp/admin",
    description: "Transport probe on the admin connector URL",
    auth: "oauth",
    category: "MCP connectors",
    usedBy: [],
    responseFields: [
      { name: "(status)", type: "401 | 405", description: "401 with WWW-Authenticate when no valid token is sent, 405 (Allow: POST) when one is" },
    ],
    notes: ["The connector does not open a server-sent event stream. Clients use POST only."],
  },
  {
    method: "POST",
    route: "/_api/mcp/teacher",
    description: "Teacher MCP connector that lets an AI assistant manage a teacher's own catalogue",
    auth: "oauth",
    category: "MCP connectors",
    usedBy: [],
    bodyParams: [
      { name: "jsonrpc", type: "'2.0'", required: true, description: "JSON-RPC version" },
      { name: "id", type: "string", required: false, description: "Request id, a string or number. Omit it for notifications" },
      { name: "method", type: "string", required: true, description: "initialize, notifications/initialized, notifications/cancelled, ping, tools/list or tools/call" },
      { name: "params", type: "object", required: false, description: "Method parameters. For tools/call: { name, arguments }" },
    ],
    responseFields: [
      { name: "jsonrpc", type: "'2.0'", description: "JSON-RPC version" },
      { name: "id", type: "string", description: "The request id" },
      { name: "result", type: "object", description: "Method result, e.g. { tools } for tools/list or the tool output for tools/call" },
    ],
    notes: [
      "Plain JSON-RPC 2.0 over the MCP Streamable HTTP transport, not superjson. Same protocol versions and 401 behaviour as the admin connector.",
      "Tools: teacher_whoami, teacher_actions, teacher_action_schema, teacher_docs, teacher_read and teacher_write. Each action maps onto a teacher console action and runs as the teacher who approved the connection.",
      "teacher_docs returns format references; \"question-format\" covers question HTML and math nodes. questions/* and question-bank/* writes convert $...$, $$...$$, \\(...\\) and \\[...\\] to math nodes, refuse formulas KaTeX cannot render or unclosed delimiters, and add formatCheck { formulas, converted, warnings } to the result.",
      "A team manager's token works on the team owner's account. A token approved while an admin impersonated the teacher acts as that teacher until it is removed.",
    ],
  },
  {
    method: "GET",
    route: "/_api/mcp/teacher",
    description: "Transport probe on the teacher connector URL",
    auth: "oauth",
    category: "MCP connectors",
    usedBy: [],
    responseFields: [
      { name: "(status)", type: "401 | 405", description: "401 with WWW-Authenticate when no valid token is sent, 405 (Allow: POST) when one is" },
    ],
  },
  {
    method: "GET",
    route: "/_api/mcp/oauth/authorize",
    description: "Shared OAuth authorization endpoint that forwards to the right connector's consent page",
    auth: "none",
    category: "MCP connectors",
    usedBy: [],
    queryParams: [
      { name: "resource", type: "string", required: true, description: "The connector URL: https://testkart.in/_api/mcp/admin or https://testkart.in/_api/mcp/teacher" },
      { name: "client_id", type: "string", required: true, description: "Client id from registration" },
      { name: "redirect_uri", type: "string", required: true, description: "One of the client's registered redirect URIs" },
      { name: "response_type", type: "'code'", required: true, description: "Always code" },
      { name: "code_challenge", type: "string", required: true, description: "PKCE challenge" },
      { name: "code_challenge_method", type: "'S256'", required: true, description: "Only S256 is accepted" },
      { name: "state", type: "string", required: false, description: "Echoed back on the redirect" },
      { name: "scope", type: "string", required: false, description: "mcp" },
    ],
    responseFields: [
      { name: "(redirect)", type: "302", description: "To /_api/mcp/admin/authorize or /_api/mcp/teacher/authorize with the same query string" },
    ],
    notes: [
      "Advertised by /.well-known/oauth-authorization-server and /.well-known/openid-configuration (issuer https://testkart.in).",
      "A missing or unknown resource renders an error page instead of redirecting.",
    ],
  },
  {
    method: "POST",
    route: "/_api/mcp/oauth/register",
    description: "Register an MCP client (RFC 7591 dynamic client registration)",
    auth: "none",
    category: "MCP connectors",
    usedBy: [],
    bodyParams: [
      { name: "redirect_uris", type: "array", required: true, description: "At least one URI. Must be https, or http on a loopback host, with no fragment" },
      { name: "client_name", type: "string", required: false, description: "Shown on the consent page. Trimmed to 200 characters, defaults to 'MCP client'" },
      { name: "grant_types", type: "array", required: false, description: "Accepted and ignored. The client always gets authorization_code and refresh_token" },
      { name: "response_types", type: "array", required: false, description: "Accepted and ignored" },
      { name: "token_endpoint_auth_method", type: "string", required: false, description: "Accepted and ignored. Clients are public (none)" },
      { name: "scope", type: "string", required: false, description: "Accepted and ignored" },
    ],
    responseFields: [
      { name: "client_id", type: "string", description: "New client id" },
      { name: "client_id_issued_at", type: "number", description: "Unix seconds" },
      { name: "client_name", type: "string", description: "Stored client name" },
      { name: "redirect_uris", type: "array", description: "Normalised redirect URIs" },
      { name: "grant_types", type: "array", description: "['authorization_code', 'refresh_token']" },
      { name: "response_types", type: "array", description: "['code']" },
      { name: "token_endpoint_auth_method", type: "'none'", description: "No client secret is issued" },
    ],
    notes: ["Plain JSON body, not superjson. Returns 201. Invalid metadata returns 400 with an RFC 7591 error code."],
  },
  {
    method: "POST",
    route: "/_api/mcp/oauth/token",
    description: "Shared OAuth token endpoint: exchange an authorization code or rotate a refresh token",
    auth: "none",
    category: "MCP connectors",
    usedBy: [],
    bodyParams: [
      { name: "grant_type", type: "'authorization_code' | 'refresh_token'", required: true, description: "Which grant to run" },
      { name: "client_id", type: "string", required: true, description: "Registered client id" },
      { name: "code", type: "string", required: false, description: "Required for authorization_code. Codes last 5 minutes and work once" },
      { name: "redirect_uri", type: "string", required: false, description: "Required for authorization_code. Must match the authorize request" },
      { name: "code_verifier", type: "string", required: false, description: "Required for authorization_code. PKCE verifier" },
      { name: "refresh_token", type: "string", required: false, description: "Required for refresh_token" },
      { name: "resource", type: "string", required: false, description: "When sent, must name the same connector the code or token belongs to" },
    ],
    responseFields: [
      { name: "access_token", type: "string", description: "Bearer token for the connector, valid 1 hour" },
      { name: "token_type", type: "'Bearer'", description: "Always Bearer" },
      { name: "expires_in", type: "number", description: "Seconds until the access token expires (3600)" },
      { name: "refresh_token", type: "string", description: "New refresh token, valid 30 days. The old one is revoked" },
      { name: "scope", type: "string", description: "Granted scope, when one was requested" },
    ],
    notes: [
      "Form-encoded body (application/x-www-form-urlencoded), not JSON. Responses carry Cache-Control: no-store.",
      "Errors use OAuth codes: invalid_request, invalid_grant (bad, expired or replayed code, failed PKCE), invalid_target (resource names another connector).",
      "A replayed refresh token is refused because each refresh revokes the previous one.",
    ],
  },
  {
    method: "GET",
    route: "/_api/mcp/admin/authorize",
    description: "Consent page for connecting an AI assistant to the admin connector",
    auth: "admin",
    category: "MCP connectors",
    usedBy: [],
    queryParams: [
      { name: "client_id", type: "string", required: true, description: "Registered client id" },
      { name: "redirect_uri", type: "string", required: true, description: "One of the client's registered redirect URIs" },
      { name: "response_type", type: "'code'", required: true, description: "Always code" },
      { name: "code_challenge", type: "string", required: true, description: "PKCE challenge" },
      { name: "code_challenge_method", type: "'S256'", required: true, description: "Only S256 is accepted" },
      { name: "state", type: "string", required: false, description: "Echoed back on the redirect" },
      { name: "scope", type: "string", required: false, description: "mcp" },
      { name: "resource", type: "string", required: false, description: "The admin connector URL" },
    ],
    responseFields: [
      { name: "(html)", type: "page", description: "Consent page naming the client and the signed-in admin, or a sign-in prompt" },
    ],
    notes: [
      "Uses the admin's existing panel session. There is no password field on this page.",
      "Invalid parameters render an error page rather than redirecting to an unverified redirect_uri.",
    ],
  },
  {
    method: "POST",
    route: "/_api/mcp/admin/authorize",
    description: "Submit the admin consent form and redirect back to the client with a code",
    auth: "admin",
    category: "MCP connectors",
    usedBy: [],
    bodyParams: [
      { name: "action", type: "'allow' | 'deny'", required: true, description: "The admin's choice" },
      { name: "client_id", type: "string", required: true, description: "Echoed from the consent page, with the other OAuth fields" },
    ],
    responseFields: [
      { name: "(redirect)", type: "302", description: "To redirect_uri with code and state, or with error=access_denied" },
    ],
    notes: [
      "Form-encoded body posted by the consent page. All OAuth fields are re-validated and the admin session is checked again.",
    ],
  },
  {
    method: "GET",
    route: "/_api/mcp/teacher/authorize",
    description: "Consent page for connecting an AI assistant to a teacher account",
    auth: "teacher",
    category: "MCP connectors",
    usedBy: [],
    queryParams: [
      { name: "client_id", type: "string", required: true, description: "Registered client id" },
      { name: "redirect_uri", type: "string", required: true, description: "One of the client's registered redirect URIs" },
      { name: "response_type", type: "'code'", required: true, description: "Always code" },
      { name: "code_challenge", type: "string", required: true, description: "PKCE challenge" },
      { name: "code_challenge_method", type: "'S256'", required: true, description: "Only S256 is accepted" },
      { name: "state", type: "string", required: false, description: "Echoed back on the redirect" },
      { name: "scope", type: "string", required: false, description: "mcp" },
      { name: "resource", type: "string", required: false, description: "The teacher connector URL" },
    ],
    responseFields: [
      { name: "(html)", type: "page", description: "Consent page, a session check, a sign-in prompt, or a wrong-account error" },
    ],
    notes: [
      "Uses the existing teacher session. A signed-in student or admin account gets a 403 wrong-account page.",
      "The page warns when the signer is a team manager or an impersonating admin.",
    ],
  },
  {
    method: "POST",
    route: "/_api/mcp/teacher/authorize",
    description: "Submit the teacher consent form and redirect back to the client with a code",
    auth: "teacher",
    category: "MCP connectors",
    usedBy: [],
    bodyParams: [
      { name: "action", type: "'allow' | 'deny'", required: true, description: "The teacher's choice" },
      { name: "client_id", type: "string", required: true, description: "Echoed from the consent page, with the other OAuth fields" },
    ],
    responseFields: [
      { name: "(redirect)", type: "302", description: "To redirect_uri with code and state, or with error=access_denied" },
    ],
    notes: ["Form-encoded body posted by the consent page. All OAuth fields are re-validated and the session is checked again."],
  },
  {
    method: "POST",
    route: "/_api/mcp/admin/register",
    description: "Register an MCP client for the admin connector only",
    auth: "none",
    category: "MCP connectors",
    usedBy: [],
    deprecated: `Use POST /_api/mcp/oauth/register instead. ${LEGACY_OAUTH}`,
    bodyParams: [
      { name: "redirect_uris", type: "array", required: true, description: "Same rules as the shared register endpoint" },
      { name: "client_name", type: "string", required: false, description: "Shown on the consent page" },
    ],
    responseFields: [
      { name: "client_id", type: "string", description: "New client id. Same response as the shared register endpoint" },
    ],
  },
  {
    method: "POST",
    route: "/_api/mcp/admin/token",
    description: "Token endpoint for the admin connector only",
    auth: "none",
    category: "MCP connectors",
    usedBy: [],
    deprecated: `Use POST /_api/mcp/oauth/token instead. ${LEGACY_OAUTH}`,
    bodyParams: [
      { name: "grant_type", type: "'authorization_code' | 'refresh_token'", required: true, description: "Same fields as the shared token endpoint" },
    ],
    responseFields: [
      { name: "access_token", type: "string", description: "Same response as the shared token endpoint" },
    ],
    notes: ["Refuses codes and refresh tokens that belong to the teacher connector."],
  },
  {
    method: "POST",
    route: "/_api/mcp/teacher/register",
    description: "Register an MCP client for the teacher connector only",
    auth: "none",
    category: "MCP connectors",
    usedBy: [],
    deprecated: `Use POST /_api/mcp/oauth/register instead. ${LEGACY_OAUTH}`,
    bodyParams: [
      { name: "redirect_uris", type: "array", required: true, description: "Same rules as the shared register endpoint" },
      { name: "client_name", type: "string", required: false, description: "Shown on the consent page" },
    ],
    responseFields: [
      { name: "client_id", type: "string", description: "New client id. Same response as the shared register endpoint" },
    ],
  },
  {
    method: "POST",
    route: "/_api/mcp/teacher/token",
    description: "Token endpoint for the teacher connector only",
    auth: "none",
    category: "MCP connectors",
    usedBy: [],
    deprecated: `Use POST /_api/mcp/oauth/token instead. ${LEGACY_OAUTH}`,
    bodyParams: [
      { name: "grant_type", type: "'authorization_code' | 'refresh_token'", required: true, description: "Same fields as the shared token endpoint" },
    ],
    responseFields: [
      { name: "access_token", type: "string", description: "Same response as the shared token endpoint" },
    ],
    notes: ["Refuses codes and refresh tokens that belong to the admin connector."],
  },
];
