/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AdminRole = "admin" | "billing_manager" | "manager" | "super_admin";

export type BankVerificationStatus = "pending" | "rejected" | "verified";

export type BlogCommentStatus = "approved" | "pending" | "rejected";

export type BlogContentType = "blog" | "knowledge_base";

export type BlogPostStatus = "archived" | "draft" | "published";

export type BundleItemType = "course" | "digital_product" | "test";

export type CallDisposition = "busy" | "callback_requested" | "connected_interested" | "connected_not_interested" | "no_answer" | "other" | "voicemail" | "wrong_number";

export type CertificateType = "course_completion" | "test_completion";

export type ContactSubmissionStatus = "archived" | "new" | "read" | "responded";

export type ContentType = "course" | "course_bundle" | "digital_product" | "live_test" | "mock_test";

export type CourseLevel = "advanced" | "beginner" | "intermediate";

export type CourseStatus = "archived" | "draft" | "published";

export type CourseTransactionStatus = "completed" | "failed" | "pending" | "refunded";

export type DigitalProductStatus = "archived" | "draft" | "published";

export type DiscountType = "fixed" | "percentage";

export type EmploymentType = "contract" | "full_time" | "internship" | "part_time";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ImageRecoveryStatus = "completed" | "failed" | "running";

export type InquiryStatus = "archived" | "contacted" | "pending" | "resolved";

export type InstituteType = "coaching" | "individual" | "institute" | "school";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LessonContentType = "pdf" | "quiz" | "text" | "video";

export type MentorshipBookingStatus = "cancelled" | "completed" | "no_show" | "scheduled";

export type MentorshipSubscriptionStatus = "active" | "cancelled" | "expired";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderStatus = "cancelled" | "completed" | "failed" | "pending" | "refunded";

export type PrizeDistributionStatus = "distributed" | "not_applicable" | "pending";

export type PrizeFundSource = "enrollment" | "teacher_wallet";

export type PromoCodeAppliesTo = "all" | "bundles" | "courses" | "digital_products" | "live_tests" | "tests";

export type QuestionType = "assertion_reason" | "comprehension" | "match_the_following" | "multiple_correct_mcq" | "numerical" | "single_correct_mcq";

export type ReviewStatus = "approved" | "pending" | "rejected";

export type SalesActivityType = "assignment_changed" | "call_logged" | "follow_up_changed" | "note_added" | "stage_changed";

export type SalesContactSource = "demo_request" | "signup";

export type SalesStage = "converted" | "follow_up" | "new" | "not_interested" | "qualified";

export type SubscriptionStatus = "active" | "cancelled" | "expired" | "pending";

export type SupportMessageSenderType = "admin" | "teacher";

export type SupportThreadStatus = "closed" | "open" | "resolved";

export type TeacherTeamRole = "manager" | "owner";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TransactionStatus = "completed" | "failed" | "pending" | "refunded";

export type UserRole = "admin" | "student" | "teacher";

export type WalletTransactionType = "prize_credit" | "prize_lock_refund" | "purchase_debit" | "withdrawal_debit";

export type WithdrawalStatus = "cancelled" | "completed" | "failed" | "pending";

export interface AdminLoginFailures {
  attemptedAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  ipAddress: string | null;
}

export interface AdminPasswordResets {
  adminId: number;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  requestedIp: string | null;
  tokenHash: string;
  usedAt: Timestamp | null;
}

export interface Admins {
  avatarFileId: string | null;
  avatarUrl: string | null;
  bio: string | null;
  createdAt: Generated<Timestamp | null>;
  email: string;
  fullName: string;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  lastLoginAt: Timestamp | null;
  passwordHash: string;
  role: Generated<AdminRole>;
  sessionInvalidatedAt: Timestamp | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface AiGenerationLogs {
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  durationMs: number | null;
  errorMessage: string | null;
  feature: string;
  id: Generated<number>;
  requestMeta: Json | null;
  status: Generated<string>;
  teacherId: number;
}

export interface BlogCategories {
  createdAt: Generated<Timestamp>;
  description: string | null;
  icon: string | null;
  id: Generated<number>;
  name: string;
  slug: string;
  sortOrder: Generated<number>;
  type: Generated<BlogContentType>;
  updatedAt: Generated<Timestamp>;
}

export interface BlogComments {
  content: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  parentId: number | null;
  postId: number;
  status: Generated<BlogCommentStatus>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface BlogPostReactions {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  postId: number;
  reaction: string;
  sessionId: string;
  updatedAt: Generated<Timestamp>;
}

export interface BlogPosts {
  authorId: number;
  categoryId: number | null;
  content: Generated<string>;
  createdAt: Generated<Timestamp>;
  excerpt: string | null;
  featuredImage: string | null;
  id: Generated<number>;
  isFeatured: Generated<boolean>;
  ogImage: string | null;
  publishedAt: Timestamp | null;
  readingTimeMinutes: Generated<number>;
  seoDescription: string | null;
  seoTitle: string | null;
  slug: string;
  status: Generated<BlogPostStatus>;
  title: string;
  type: Generated<BlogContentType>;
  updatedAt: Generated<Timestamp>;
  viewCount: Generated<number>;
}

export interface BlogPostTags {
  postId: number;
  tagId: number;
}

export interface BlogTags {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  slug: string;
}

export interface BundleEnrollments {
  bundleId: number;
  createdAt: Generated<Timestamp>;
  enrolledAt: Generated<Timestamp>;
  id: Generated<number>;
  orderId: number | null;
  studentId: number;
}

export interface CareerApplications {
  careerPostingId: number;
  coverLetter: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  linkedinUrl: string | null;
  name: string;
  phone: string | null;
  resumeFileId: string | null;
  resumeUrl: string | null;
}

export interface CareerPostings {
  createdAt: Generated<Timestamp>;
  department: string | null;
  description: string;
  employmentType: Generated<EmploymentType>;
  experienceLevel: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  location: string | null;
  orderIndex: Generated<number>;
  requirements: string | null;
  salaryRange: string | null;
  slug: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface CartItems {
  addedAt: Generated<Timestamp | null>;
  courseId: number | null;
  digitalProductId: number | null;
  id: Generated<number>;
  mockTestId: number | null;
  userId: number;
}

export interface Certificates {
  certificateData: Json;
  certificateNumber: string;
  certificateType: CertificateType;
  completionDate: Timestamp;
  courseId: number | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  issuedAt: Generated<Timestamp>;
  pdfUrl: string | null;
  scorePercentage: Numeric | null;
  studentId: number;
  testItemId: number | null;
}

export interface ContactSubmissions {
  createdAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  message: string;
  name: string;
  status: Generated<ContactSubmissionStatus | null>;
  subject: string | null;
}

export interface ContentReviews {
  adminNotes: string | null;
  contentId: number;
  contentType: ContentType;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  reviewedAt: Timestamp | null;
  reviewedBy: number | null;
  status: Generated<ReviewStatus>;
  teacherId: number;
  updatedAt: Generated<Timestamp>;
}

export interface CourseBundleItems {
  bundleId: number;
  courseId: number | null;
  createdAt: Generated<Timestamp>;
  digitalProductId: number | null;
  id: Generated<number>;
  itemType: BundleItemType;
  mockTestId: number | null;
  orderIndex: Generated<number>;
}

export interface CourseBundles {
  createdAt: Generated<Timestamp>;
  description: string | null;
  discountPercentage: Generated<Numeric | null>;
  id: Generated<number>;
  introVideoFileId: string | null;
  introVideoUrl: string | null;
  isPublished: Generated<boolean>;
  originalPrice: Numeric;
  price: Numeric;
  publishedAt: Timestamp | null;
  slug: string;
  teacherId: number;
  thumbnailFileId: string | null;
  thumbnailUrl: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface CourseEnrollments {
  completedAt: Timestamp | null;
  completionPercentage: Generated<number>;
  courseId: number;
  enrolledAt: Generated<Timestamp>;
  id: Generated<number>;
  lastAccessedAt: Generated<Timestamp>;
  studentId: number;
}

export interface CourseLessons {
  contentFileId: string | null;
  contentType: LessonContentType;
  contentUrl: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  durationMinutes: Generated<number | null>;
  id: Generated<number>;
  isPreview: Generated<boolean>;
  orderIndex: number;
  sectionId: number;
  textContent: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface CourseMedia {
  courseId: number;
  createdAt: Generated<Timestamp>;
  fileId: string | null;
  id: Generated<number>;
  mediaType: string;
  mediaUrl: string;
  orderIndex: Generated<number>;
}

export interface CourseProgress {
  completedAt: Generated<Timestamp>;
  enrollmentId: number;
  id: Generated<number>;
  lessonId: number;
}

export interface Courses {
  category: string | null;
  createdAt: Generated<Timestamp>;
  description: string;
  estimatedDurationMinutes: Generated<number | null>;
  examId: number | null;
  examName: string | null;
  id: Generated<number>;
  introVideoFileId: string | null;
  introVideoUrl: string | null;
  language: string | null;
  level: Generated<CourseLevel>;
  price: Generated<Numeric>;
  publishedAt: Timestamp | null;
  rating: Numeric | null;
  reviewsCount: Generated<number>;
  slug: string;
  status: Generated<CourseStatus>;
  teacherId: number;
  thumbnailFileId: string | null;
  thumbnailImageFileId: string | null;
  thumbnailImageUrl: string | null;
  thumbnailUrl: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
  views: Generated<number>;
}

export interface CourseSections {
  courseId: number;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  orderIndex: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface CourseTransactions {
  amount: Numeric;
  completedAt: Timestamp | null;
  courseId: number;
  createdAt: Generated<Timestamp>;
  discountAmount: Generated<Numeric>;
  id: Generated<number>;
  paymentMethod: Generated<string>;
  payuTransactionId: string | null;
  promoCodeId: number | null;
  status: Generated<CourseTransactionStatus>;
  studentId: number;
}

export interface DeletedAccounts {
  deletedAt: Generated<Timestamp>;
  displayName: string;
  email: string | null;
  id: Generated<number>;
  mobileNumber: string | null;
  originalUserId: number;
  reason: string | null;
  registeredAt: Timestamp | null;
  role: string;
}

export interface DigitalProductFiles {
  createdAt: Generated<Timestamp>;
  fileId: string | null;
  fileSizeBytes: Int8 | null;
  fileUrl: string;
  id: Generated<number>;
  orderIndex: Generated<number>;
  pageCount: number | null;
  productId: number;
  title: string;
}

export interface DigitalProductPurchases {
  downloadCount: Generated<number | null>;
  id: Generated<number>;
  lastDownloadedAt: Timestamp | null;
  orderId: number | null;
  productId: number;
  purchasedAt: Generated<Timestamp | null>;
  studentId: number;
}

export interface DigitalProducts {
  category: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  examId: number | null;
  examName: string | null;
  fileSizeBytes: Int8 | null;
  id: Generated<number>;
  isPublished: Generated<boolean | null>;
  language: string | null;
  pageCount: number | null;
  pdfFileId: string | null;
  pdfUrl: string;
  previewPages: Generated<number | null>;
  price: Generated<Numeric>;
  publishedAt: Timestamp | null;
  rating: Numeric | null;
  reviewsCount: Generated<number | null>;
  shortDescription: string | null;
  slug: string;
  status: Generated<DigitalProductStatus | null>;
  tags: string[] | null;
  teacherId: number;
  thumbnailFileId: string | null;
  thumbnailUrl: string | null;
  title: string;
  totalPurchases: Generated<number | null>;
  updatedAt: Generated<Timestamp | null>;
  views: Generated<number>;
}

export interface EmailOtps {
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<number>;
  otpCode: string;
  userId: number | null;
  verifiedAt: Timestamp | null;
}

export interface EmailTemplates {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  htmlContent: string;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  name: string;
  placeholders: Generated<Json | null>;
  subject: string;
  templateKey: string;
  textContent: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface ExamCategories {
  categoryName: string;
  categorySlug: string;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  orderIndex: Generated<number | null>;
}

export interface ExamContentPages {
  aiGeneratedAt: Timestamp | null;
  content: string | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  examId: number;
  faqItems: Json | null;
  id: Generated<number>;
  pageType: string;
  publishedAt: Timestamp | null;
  publishedContent: string | null;
  publishedDescription: string | null;
  publishedFaqItems: Json | null;
  publishedSeoDescription: string | null;
  publishedSeoTitle: string | null;
  publishedTitle: string | null;
  readyForReviewAt: Timestamp | null;
  readyForReviewByAdminId: number | null;
  reviewedAt: Timestamp | null;
  reviewedByAdminId: number | null;
  seoDescription: string | null;
  seoTitle: string | null;
  source: Generated<string>;
  status: Generated<string>;
  title: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Exams {
  aiGenerationPrompt: string | null;
  categoryId: number;
  contentDueDate: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  examName: string;
  examSlug: string;
  fullName: string;
  id: Generated<number>;
  orderIndex: Generated<number | null>;
  ownerTag: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface ExamSubjects {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  examId: number;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  orderIndex: Generated<number | null>;
  subjectName: string;
  subjectSlug: string;
  syllabusTopics: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface ImageRecoveryJobs {
  checked: Generated<number>;
  completedAt: Timestamp | null;
  errors: Generated<Json>;
  executionId: string;
  failedCount: Generated<number>;
  id: Generated<number>;
  missing: Generated<number>;
  recovered: Generated<number>;
  skipped: Generated<number>;
  startedAt: Generated<Timestamp>;
  status: Generated<ImageRecoveryStatus>;
  totalKeys: Generated<number>;
}

export interface InvoiceCounters {
  lastNumber: Generated<number>;
  series: string;
  updatedAt: Generated<Timestamp>;
}

export interface LiveTestEnrollments {
  createdAt: Generated<Timestamp>;
  enrolledAt: Generated<Timestamp>;
  id: Generated<number>;
  liveTestId: number;
  paymentOrderId: number | null;
  studentId: number;
}

export interface LiveTestPrizeDistributions {
  actualAmount: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  liveTestId: number;
  originalAmount: Generated<Numeric>;
  rank: number;
  studentId: number;
}

export interface LiveTests {
  actualTotalDistributed: Generated<Numeric>;
  createdAt: Generated<Timestamp>;
  description: string | null;
  discountPrice: Numeric | null;
  endTime: Timestamp;
  enrolledCount: Generated<number>;
  firstPrize: Generated<Numeric>;
  hasPrizes: Generated<boolean>;
  id: Generated<number>;
  introVideoFileId: string | null;
  introVideoUrl: string | null;
  isActive: Generated<boolean>;
  isFree: Generated<boolean>;
  maxSeats: number;
  mockTestId: number;
  price: Generated<Numeric>;
  prizeDistributionStatus: Generated<PrizeDistributionStatus>;
  prizeFundSource: PrizeFundSource | null;
  prizeTiers: Json | null;
  registrationDeadline: Timestamp | null;
  secondPrize: Generated<Numeric>;
  startTime: Timestamp | null;
  teacherId: number;
  thirdPrize: Generated<Numeric>;
  thumbnailFileId: string | null;
  thumbnailUrl: string | null;
  title: string;
  totalPrizePool: Generated<Numeric>;
  updatedAt: Generated<Timestamp>;
  viewCount: Generated<number>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface McpOauthClients {
  clientId: string;
  clientName: string;
  createdAt: Generated<Timestamp>;
  redirectUris: Json;
}

export interface McpOauthCodes {
  adminId: number | null;
  audience: Generated<string>;
  clientId: string;
  codeChallenge: string;
  codeChallengeMethod: string;
  codeHash: string;
  consumedAt: Timestamp | null;
  expiresAt: Timestamp;
  impersonatorAdminId: number | null;
  redirectUri: string;
  resource: string | null;
  scope: string | null;
  userId: number | null;
}

export interface McpOauthTokens {
  accessExpiresAt: Timestamp;
  accessTokenHash: string;
  adminId: number | null;
  audience: Generated<string>;
  clientId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  lastUsedAt: Timestamp | null;
  refreshExpiresAt: Timestamp | null;
  refreshTokenHash: string | null;
  revokedAt: Timestamp | null;
  scope: string | null;
  sessionId: string | null;
  userId: number | null;
}

export interface MentorshipAvailability {
  createdAt: Generated<Timestamp | null>;
  dayOfWeek: number;
  endTime: string;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  startTime: string;
  teacherId: number;
}

export interface MentorshipBlockedDates {
  blockedDate: Timestamp;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  reason: string | null;
  teacherId: number;
}

export interface MentorshipBookings {
  amountPaid: Generated<Numeric | null>;
  cancellationReason: string | null;
  cancelledAt: Timestamp | null;
  cancelledBy: string | null;
  createdAt: Generated<Timestamp | null>;
  durationMinutes: number;
  id: Generated<number>;
  meetingLink: string | null;
  notes: string | null;
  orderId: number | null;
  scheduledAt: Timestamp;
  sessionTypeId: number | null;
  status: Generated<MentorshipBookingStatus | null>;
  studentId: number;
  studentNotes: string | null;
  subscriptionId: number | null;
  teacherId: number;
  updatedAt: Generated<Timestamp | null>;
}

export interface MentorshipPlans {
  callDurationMinutes: Generated<number>;
  callsPerMonth: Generated<number>;
  createdAt: Generated<Timestamp | null>;
  currentMentees: Generated<number | null>;
  description: string | null;
  durationWeeks: Generated<number>;
  features: Generated<Json | null>;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  maxMentees: number | null;
  price: Numeric;
  teacherId: number;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface MentorshipSessionTypes {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  durationMinutes: Generated<number>;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  price: Numeric;
  teacherId: number;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface MentorshipSubscriptions {
  amountPaid: Numeric;
  callsRemaining: number;
  createdAt: Generated<Timestamp | null>;
  endDate: Timestamp;
  id: Generated<number>;
  orderId: number | null;
  planId: number;
  startDate: Timestamp;
  status: Generated<MentorshipSubscriptionStatus | null>;
  studentId: number;
  teacherId: number;
  updatedAt: Generated<Timestamp | null>;
}

export interface Meta {
  field: string;
  id: Generated<number>;
  value: string | null;
}

export interface MobileOtps {
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  ipAddress: string | null;
  mobileNumber: string;
  otpCode: string;
  userId: number | null;
  verifiedAt: Timestamp | null;
}

export interface MockTestEnrollments {
  createdAt: Generated<Timestamp>;
  enrolledAt: Generated<Timestamp>;
  id: Generated<number>;
  mockTestId: number;
  orderId: number | null;
  studentId: number;
}

export interface MockTestItems {
  calculatorEnabled: Generated<boolean>;
  createdAt: Generated<Timestamp | null>;
  deletedAt: Timestamp | null;
  description: string | null;
  durationMinutes: Generated<number>;
  id: Generated<number>;
  isFree: Generated<boolean>;
  orderIndex: Generated<number>;
  packageId: number;
  questionWiseTiming: Generated<boolean>;
  scheduledDate: Timestamp | null;
  subject: Generated<string>;
  subjectWiseTiming: Generated<boolean>;
  title: string;
  totalQuestions: Generated<number>;
}

export interface MockTests {
  createdAt: Generated<Timestamp | null>;
  creatorName: string | null;
  deletedAt: Timestamp | null;
  description: string | null;
  discountPrice: Numeric | null;
  durationMinutes: Generated<number>;
  examId: number | null;
  examName: string | null;
  freeTestsCount: Generated<number>;
  id: Generated<number>;
  introVideoFileId: string | null;
  introVideoUrl: string | null;
  isFree: Generated<boolean>;
  isPublished: Generated<boolean>;
  language: string | null;
  longDescription: string | null;
  price: Generated<Numeric>;
  rating: Numeric | null;
  requirements: Json | null;
  reviewsCount: Generated<number>;
  slug: string;
  studentsEnrolled: Generated<number>;
  subject: string | null;
  teacherId: number;
  thumbnailFileId: string | null;
  thumbnailUrl: string | null;
  title: string;
  totalQuestions: Generated<number>;
  totalTests: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
  views: Generated<number>;
  wasEverPublished: Generated<boolean>;
  whatYouLearn: Json | null;
}

export interface NewsCoverage {
  coverageUrl: string | null;
  createdAt: Generated<Timestamp>;
  excerpt: string | null;
  id: Generated<number>;
  imageFileId: string | null;
  imageUrl: string;
  isPublished: Generated<boolean>;
  keywords: string | null;
  previousSlugs: Generated<string[]>;
  publicationName: string | null;
  publishedAt: Generated<Timestamp>;
  slug: string;
  title: string;
  updatedAt: Generated<Timestamp>;
  writeup: string;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  provider: string;
  providerEmail: string;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectToPath: string | null;
  redirectUrl: string;
  requestedRole: Generated<string>;
  state: string;
  userId: number | null;
}

export interface OrderItems {
  courseId: number | null;
  createdAt: Generated<Timestamp | null>;
  digitalProductId: number | null;
  discountAmount: Generated<Numeric>;
  id: Generated<number>;
  mentorshipBookingId: number | null;
  mentorshipPlanId: number | null;
  mentorshipSessionTypeId: number | null;
  mockTestId: number | null;
  orderId: number;
  platformFeePercentage: Generated<Numeric>;
  priceAtPurchase: Numeric;
  quantity: Generated<number>;
}

export interface Orders {
  bundleId: number | null;
  createdAt: Generated<Timestamp | null>;
  discountAmount: Generated<Numeric>;
  emailsSentAt: Timestamp | null;
  id: Generated<number>;
  invoiceEmailSentAt: Timestamp | null;
  invoiceNumber: string | null;
  paymentBankMessage: string | null;
  paymentErrorCode: string | null;
  paymentErrorMessage: string | null;
  paymentGatewayStatus: string | null;
  paymentMethod: string | null;
  paymentTransactionId: string | null;
  platformFeePercentage: Numeric | null;
  promoCodeId: number | null;
  status: Generated<OrderStatus>;
  totalAmount: Numeric;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface OtpVerifyFailures {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  identifier: string;
  ipAddress: string | null;
}

export interface PdfPreviewPages {
  createdAt: Generated<Timestamp>;
  height: number;
  imageKey: string;
  pageNumber: number;
  sourcePageCount: number;
  sourceUrl: string;
  width: number;
}

export interface PdfRecoveryJobs {
  checked: Generated<number>;
  completedAt: Timestamp | null;
  errors: Generated<Json>;
  executionId: string;
  failedCount: Generated<number>;
  id: Generated<number>;
  missing: Generated<number>;
  recovered: Generated<number>;
  skipped: Generated<number>;
  startedAt: Generated<Timestamp>;
  status: Generated<string>;
  totalKeys: Generated<number>;
}

export interface PlatformScripts {
  footerScript: string | null;
  headerScript: string | null;
  id: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
  updatedByAdminId: number | null;
}

export interface PlatformSettings {
  id: Generated<number>;
  settingKey: string;
  settingValue: string;
  updatedAt: Generated<Timestamp | null>;
  updatedByAdminId: number | null;
}

export interface PromoCodes {
  appliesTo: Generated<PromoCodeAppliesTo>;
  code: string;
  createdAt: Generated<Timestamp>;
  createdByAdminId: number | null;
  createdByTeacherId: number | null;
  discountType: DiscountType;
  discountValue: Numeric;
  id: Generated<number>;
  isActive: Generated<boolean>;
  maxDiscountAmount: Generated<Numeric | null>;
  minPurchaseAmount: Generated<Numeric | null>;
  perUserLimit: number | null;
  targetItemIds: number[] | null;
  updatedAt: Generated<Timestamp>;
  usageCount: Generated<number>;
  usageLimit: number | null;
  validFrom: Generated<Timestamp>;
  validUntil: Timestamp | null;
}

export interface PromoCodeUsages {
  courseTransactionId: number | null;
  discountAmount: Numeric;
  id: Generated<number>;
  orderId: number | null;
  promoCodeId: number;
  usedAt: Generated<Timestamp>;
  userId: number;
}

export interface QuestionBank {
  correctOption: string | null;
  correctOptions: string[] | null;
  createdAt: Generated<Timestamp | null>;
  durationSeconds: number | null;
  examId: number | null;
  explanation: string | null;
  id: Generated<number>;
  matchData: Json | null;
  negativeMarks: Generated<Numeric | null>;
  numericalAnswer: Numeric | null;
  numericalTolerance: Generated<Numeric | null>;
  optionA: string | null;
  optionB: string | null;
  optionC: string | null;
  optionD: string | null;
  optionE: string | null;
  paragraphText: string | null;
  partialMarking: Generated<boolean | null>;
  positiveMarks: Generated<Numeric | null>;
  questionText: string;
  questionType: Generated<QuestionType | null>;
  sourceMockTestId: number | null;
  sourceTestItemId: number | null;
  sourceTestQuestionId: number | null;
  subjectName: string | null;
  tags: string[] | null;
  teacherId: number;
  updatedAt: Generated<Timestamp | null>;
}

export interface Reviews {
  courseId: number | null;
  createdAt: Generated<Timestamp | null>;
  digitalProductId: number | null;
  id: Generated<number>;
  mockTestId: number | null;
  rating: number;
  reviewerName: string;
  reviewText: string | null;
  testItemId: number | null;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface SalesContactActivities {
  activityType: SalesActivityType;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  details: string | null;
  id: Generated<number>;
  newValue: string | null;
  oldValue: string | null;
  salesContactId: number;
}

export interface SalesContactNotes {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  disposition: CallDisposition | null;
  id: Generated<number>;
  note: string;
  salesContactId: number;
}

export interface SalesContacts {
  assignedToAdminId: number | null;
  createdAt: Generated<Timestamp>;
  followUpDate: Timestamp | null;
  id: Generated<number>;
  lastContactedAt: Timestamp | null;
  leadEmail: string | null;
  leadExpertise: string | null;
  leadName: string | null;
  leadPhone: string | null;
  preferredCallDate: Timestamp | null;
  preferredCallSlot: string | null;
  source: Generated<SalesContactSource>;
  stage: Generated<SalesStage>;
  updatedAt: Generated<Timestamp>;
  userId: number | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  impersonatorAdminId: number | null;
  lastAccessed: Generated<Timestamp | null>;
  redirectToPath: string | null;
  userId: number;
}

export interface StaticPages {
  content: string;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  slug: string;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface StudentBankDetails {
  bankAccountHolderName: string;
  bankAccountNumber: string;
  bankIfscCode: string;
  bankName: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  panCardImageBase64: string;
  panNumber: string;
  rejectionReason: string | null;
  studentId: number;
  updatedAt: Generated<Timestamp>;
  upiId: string | null;
  verificationStatus: Generated<BankVerificationStatus>;
}

export interface StudentWalletTransactions {
  amount: Numeric;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  referenceId: number | null;
  studentId: number;
  transactionType: WalletTransactionType;
}

export interface StudentWithdrawals {
  amount: Numeric;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  notes: string | null;
  processedDate: Timestamp | null;
  requestedDate: Generated<Timestamp | null>;
  status: Generated<WithdrawalStatus>;
  studentId: number;
  transactionId: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface SubjectSections {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  maxAttemptsAllowed: number | null;
  orderIndex: Generated<number>;
  sectionName: string;
  subjectId: number;
}

export interface SubscriptionPlans {
  billingCycle: Generated<string>;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  durationDays: number;
  features: Json | null;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  name: string;
  platformFeePercentage: Generated<Numeric>;
  price: Numeric;
}

export interface SubscriptionTransactions {
  amount: Numeric;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  invoiceEmailSentAt: Timestamp | null;
  invoiceNumber: string | null;
  notes: string | null;
  paymentBankMessage: string | null;
  paymentErrorCode: string | null;
  paymentErrorMessage: string | null;
  paymentGatewayStatus: string | null;
  paymentMethod: string | null;
  planId: number;
  status: Generated<TransactionStatus>;
  subscriptionId: number | null;
  teacherId: number;
  transactionDate: Generated<Timestamp | null>;
  transactionId: string | null;
}

export interface SupportMessageAttachments {
  contentType: string;
  createdAt: Generated<Timestamp>;
  fileKey: string;
  fileName: string;
  fileUrl: string;
  id: Generated<number>;
  messageId: number;
  sizeBytes: number;
}

export interface SupportMessages {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isRead: Generated<boolean>;
  messageText: string;
  senderId: number;
  senderType: SupportMessageSenderType;
  threadId: number;
}

export interface SupportThreads {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  lastMessageAt: Generated<Timestamp>;
  status: Generated<SupportThreadStatus>;
  subject: string;
  teacherId: number | null;
  updatedAt: Generated<Timestamp>;
}

export interface TeacherBankDetails {
  bankAccountHolderName: string;
  bankAccountNumber: string;
  bankIfscCode: string;
  bankName: string;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  panCardImageBase64: string;
  panNumber: string;
  rejectionReason: string | null;
  teacherId: number;
  updatedAt: Generated<Timestamp>;
  upiId: string | null;
  verificationStatus: Generated<BankVerificationStatus>;
}

export interface TeacherInquiries {
  adminNotes: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  instituteName: string | null;
  message: string | null;
  name: string;
  phone: string;
  status: Generated<InquiryStatus>;
  updatedAt: Generated<Timestamp>;
}

export interface TeacherSponsoredEnrollments {
  bundleId: number | null;
  commissionAmount: Numeric;
  contentType: Generated<string>;
  courseId: number | null;
  createdAt: Generated<Timestamp | null>;
  digitalProductId: number | null;
  enrolledAt: Generated<Timestamp | null>;
  id: Generated<number>;
  mockTestId: number | null;
  notes: string | null;
  orderId: number | null;
  paymentMethod: string;
  paymentTransactionId: string | null;
  platformFeePercentage: Numeric;
  studentId: number | null;
  studentPhone: string;
  teacherId: number;
  temporaryPasswordSent: Generated<boolean | null>;
  testPrice: Numeric;
  wasNewUser: Generated<boolean | null>;
}

export interface TeacherSubscriptions {
  adminNote: string | null;
  autoRenew: Generated<boolean | null>;
  createdAt: Generated<Timestamp | null>;
  endDate: Timestamp | null;
  id: Generated<number>;
  lastChargeDate: Timestamp | null;
  mandateEndDate: Timestamp | null;
  mandateFrequency: string | null;
  mandateId: string | null;
  mandateMaxAmount: Numeric | null;
  mandatePaymentMode: Generated<string | null>;
  mandateStartDate: Timestamp | null;
  mandateStatus: string | null;
  nextChargeDate: Timestamp | null;
  paymentMethod: string | null;
  planId: number;
  platformFeeOverride: Generated<Numeric | null>;
  preDebitSentAt: Timestamp | null;
  startDate: Timestamp | null;
  status: Generated<SubscriptionStatus>;
  teacherId: number;
  updatedAt: Generated<Timestamp | null>;
}

export interface TeacherTeamMembers {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  invitedPhone: string;
  memberUserId: number;
  role: Generated<TeacherTeamRole>;
  status: Generated<string>;
  teacherId: number;
}

export interface TeacherWithdrawals {
  amount: Numeric;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  notes: string | null;
  processedDate: Timestamp | null;
  requestedDate: Generated<Timestamp | null>;
  status: Generated<WithdrawalStatus>;
  teacherId: number;
  transactionId: string | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface TeacherWorkExperiences {
  companyName: string;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  endDate: Timestamp | null;
  id: Generated<number>;
  isCurrent: Generated<boolean | null>;
  location: string | null;
  position: string;
  startDate: Timestamp;
  teacherId: number;
  updatedAt: Generated<Timestamp | null>;
}

export interface TestAttemptAnswers {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  isCorrect: boolean;
  marksObtained: Generated<Numeric | null>;
  matchAnswers: Json | null;
  numericalAnswer: Numeric | null;
  questionId: number;
  selectedOption: string | null;
  selectedOptions: string[] | null;
  testAttemptId: number;
}

export interface TestAttempts {
  completedAt: Timestamp | null;
  id: Generated<number>;
  score: Numeric | null;
  startedAt: Generated<Timestamp | null>;
  studentId: number;
  testId: number;
  totalQuestions: number;
}

export interface TestItemSubjects {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  durationMinutes: number | null;
  id: Generated<number>;
  maxAttemptsAllowed: number | null;
  orderIndex: Generated<number>;
  subjectName: string;
  testItemId: number;
}

export interface TestQuestions {
  aiGenerationMetadata: Json | null;
  correctOption: string | null;
  correctOptions: string[] | null;
  createdAt: Generated<Timestamp | null>;
  durationSeconds: number | null;
  explanation: string | null;
  id: Generated<number>;
  isAiGenerated: Generated<boolean | null>;
  markedForReview: Generated<boolean>;
  matchData: Json | null;
  negativeMarks: Generated<Numeric | null>;
  numericalAnswer: Numeric | null;
  numericalTolerance: Generated<Numeric | null>;
  optionA: string | null;
  optionB: string | null;
  optionC: string | null;
  optionD: string | null;
  optionE: string | null;
  orderIndex: Generated<number>;
  paragraphId: number | null;
  paragraphText: string | null;
  partialMarking: Generated<boolean | null>;
  positiveMarks: Generated<Numeric | null>;
  questionText: string;
  questionType: Generated<QuestionType | null>;
  sectionId: number | null;
  sourceBankQuestionId: number | null;
  subjectId: number | null;
  testId: number;
}

export interface UploadedFiles {
  createdAt: Generated<Timestamp>;
  key: string;
  ownerUserId: number | null;
}

export interface UploadLimits {
  courseIntroVideoMaxMb: Generated<number>;
  coursePdfMaxMb: Generated<number>;
  digitalProductPdfMaxMb: Generated<number>;
  id: Generated<number>;
  kycDocumentMaxMb: Generated<number>;
  lessonVideoMaxMb: Generated<number>;
  profilePictureMaxMb: Generated<number>;
  richTextImageMaxMb: Generated<number>;
  thumbnailMaxMb: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  academyName: string | null;
  avatarFileId: string | null;
  avatarUrl: string | null;
  awardsCertificates: Generated<Json | null>;
  billingDetails: Json | null;
  bio: string | null;
  createdAt: Generated<Timestamp | null>;
  currentOccupation: string | null;
  discoverySource: string | null;
  displayName: string;
  email: string | null;
  emailVerified: Generated<boolean>;
  expertiseAreas: Generated<Json | null>;
  goals: string | null;
  id: Generated<number>;
  instituteType: InstituteType | null;
  isActive: Generated<boolean>;
  isVerified: Generated<boolean>;
  languages: Generated<Json | null>;
  location: string | null;
  mentorshipPrice15Min: Generated<Numeric | null>;
  mentorshipPrice30Min: Generated<Numeric | null>;
  mentorshipPrice60Min: Generated<Numeric | null>;
  mobileNumber: string | null;
  mobileVerified: Generated<boolean>;
  onboardingCompleted: Generated<boolean>;
  productInterest: Json | null;
  publicEmail: string | null;
  publicPhone: string | null;
  responseTime: string | null;
  role: UserRole;
  schoolCollegeName: string | null;
  signupSource: string | null;
  slug: string | null;
  socialLinks: Generated<Json | null>;
  tagline: string | null;
  targetExams: Json | null;
  teachingCategories: Json | null;
  teachingExperienceLevel: string | null;
  updatedAt: Generated<Timestamp | null>;
  websiteUrl: string | null;
  yearsOfExperience: number | null;
}

export interface WellKnownFiles {
  content: Generated<string>;
  displayName: string;
  fileKey: string;
  id: Generated<number>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  adminLoginFailures: AdminLoginFailures;
  adminPasswordResets: AdminPasswordResets;
  admins: Admins;
  aiGenerationLogs: AiGenerationLogs;
  blogCategories: BlogCategories;
  blogComments: BlogComments;
  blogPostReactions: BlogPostReactions;
  blogPosts: BlogPosts;
  blogPostTags: BlogPostTags;
  blogTags: BlogTags;
  bundleEnrollments: BundleEnrollments;
  careerApplications: CareerApplications;
  careerPostings: CareerPostings;
  cartItems: CartItems;
  certificates: Certificates;
  contactSubmissions: ContactSubmissions;
  contentReviews: ContentReviews;
  courseBundleItems: CourseBundleItems;
  courseBundles: CourseBundles;
  courseEnrollments: CourseEnrollments;
  courseLessons: CourseLessons;
  courseMedia: CourseMedia;
  courseProgress: CourseProgress;
  courses: Courses;
  courseSections: CourseSections;
  courseTransactions: CourseTransactions;
  deletedAccounts: DeletedAccounts;
  digitalProductFiles: DigitalProductFiles;
  digitalProductPurchases: DigitalProductPurchases;
  digitalProducts: DigitalProducts;
  emailOtps: EmailOtps;
  emailTemplates: EmailTemplates;
  examCategories: ExamCategories;
  examContentPages: ExamContentPages;
  exams: Exams;
  examSubjects: ExamSubjects;
  imageRecoveryJobs: ImageRecoveryJobs;
  invoiceCounters: InvoiceCounters;
  liveTestEnrollments: LiveTestEnrollments;
  liveTestPrizeDistributions: LiveTestPrizeDistributions;
  liveTests: LiveTests;
  loginAttempts: LoginAttempts;
  mcpOauthClients: McpOauthClients;
  mcpOauthCodes: McpOauthCodes;
  mcpOauthTokens: McpOauthTokens;
  mentorshipAvailability: MentorshipAvailability;
  mentorshipBlockedDates: MentorshipBlockedDates;
  mentorshipBookings: MentorshipBookings;
  mentorshipPlans: MentorshipPlans;
  mentorshipSessionTypes: MentorshipSessionTypes;
  mentorshipSubscriptions: MentorshipSubscriptions;
  meta: Meta;
  mobileOtps: MobileOtps;
  mockTestEnrollments: MockTestEnrollments;
  mockTestItems: MockTestItems;
  mockTests: MockTests;
  newsCoverage: NewsCoverage;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  orderItems: OrderItems;
  orders: Orders;
  otpVerifyFailures: OtpVerifyFailures;
  pdfPreviewPages: PdfPreviewPages;
  pdfRecoveryJobs: PdfRecoveryJobs;
  platformScripts: PlatformScripts;
  platformSettings: PlatformSettings;
  promoCodes: PromoCodes;
  promoCodeUsages: PromoCodeUsages;
  questionBank: QuestionBank;
  reviews: Reviews;
  salesContactActivities: SalesContactActivities;
  salesContactNotes: SalesContactNotes;
  salesContacts: SalesContacts;
  sessions: Sessions;
  staticPages: StaticPages;
  studentBankDetails: StudentBankDetails;
  studentWalletTransactions: StudentWalletTransactions;
  studentWithdrawals: StudentWithdrawals;
  subjectSections: SubjectSections;
  subscriptionPlans: SubscriptionPlans;
  subscriptionTransactions: SubscriptionTransactions;
  supportMessageAttachments: SupportMessageAttachments;
  supportMessages: SupportMessages;
  supportThreads: SupportThreads;
  teacherBankDetails: TeacherBankDetails;
  teacherInquiries: TeacherInquiries;
  teacherSponsoredEnrollments: TeacherSponsoredEnrollments;
  teacherSubscriptions: TeacherSubscriptions;
  teacherTeamMembers: TeacherTeamMembers;
  teacherWithdrawals: TeacherWithdrawals;
  teacherWorkExperiences: TeacherWorkExperiences;
  testAttemptAnswers: TestAttemptAnswers;
  testAttempts: TestAttempts;
  testItemSubjects: TestItemSubjects;
  testQuestions: TestQuestions;
  uploadedFiles: UploadedFiles;
  uploadLimits: UploadLimits;
  userPasswords: UserPasswords;
  users: Users;
  wellKnownFiles: WellKnownFiles;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const AdminRoleArrayValues: [AdminRole, ...AdminRole[]] = ["admin","billing_manager","manager","super_admin"];
export const BankVerificationStatusArrayValues: [BankVerificationStatus, ...BankVerificationStatus[]] = ["pending","rejected","verified"];
export const BlogCommentStatusArrayValues: [BlogCommentStatus, ...BlogCommentStatus[]] = ["approved","pending","rejected"];
export const BlogContentTypeArrayValues: [BlogContentType, ...BlogContentType[]] = ["blog","knowledge_base"];
export const BlogPostStatusArrayValues: [BlogPostStatus, ...BlogPostStatus[]] = ["archived","draft","published"];
export const BundleItemTypeArrayValues: [BundleItemType, ...BundleItemType[]] = ["course","digital_product","test"];
export const CallDispositionArrayValues: [CallDisposition, ...CallDisposition[]] = ["busy","callback_requested","connected_interested","connected_not_interested","no_answer","other","voicemail","wrong_number"];
export const CertificateTypeArrayValues: [CertificateType, ...CertificateType[]] = ["course_completion","test_completion"];
export const ContactSubmissionStatusArrayValues: [ContactSubmissionStatus, ...ContactSubmissionStatus[]] = ["archived","new","read","responded"];
export const ContentTypeArrayValues: [ContentType, ...ContentType[]] = ["course","course_bundle","digital_product","live_test","mock_test"];
export const CourseLevelArrayValues: [CourseLevel, ...CourseLevel[]] = ["advanced","beginner","intermediate"];
export const CourseStatusArrayValues: [CourseStatus, ...CourseStatus[]] = ["archived","draft","published"];
export const CourseTransactionStatusArrayValues: [CourseTransactionStatus, ...CourseTransactionStatus[]] = ["completed","failed","pending","refunded"];
export const DigitalProductStatusArrayValues: [DigitalProductStatus, ...DigitalProductStatus[]] = ["archived","draft","published"];
export const DiscountTypeArrayValues: [DiscountType, ...DiscountType[]] = ["fixed","percentage"];
export const EmploymentTypeArrayValues: [EmploymentType, ...EmploymentType[]] = ["contract","full_time","internship","part_time"];
export const ImageRecoveryStatusArrayValues: [ImageRecoveryStatus, ...ImageRecoveryStatus[]] = ["completed","failed","running"];
export const InquiryStatusArrayValues: [InquiryStatus, ...InquiryStatus[]] = ["archived","contacted","pending","resolved"];
export const InstituteTypeArrayValues: [InstituteType, ...InstituteType[]] = ["coaching","individual","institute","school"];
export const LessonContentTypeArrayValues: [LessonContentType, ...LessonContentType[]] = ["pdf","quiz","text","video"];
export const MentorshipBookingStatusArrayValues: [MentorshipBookingStatus, ...MentorshipBookingStatus[]] = ["cancelled","completed","no_show","scheduled"];
export const MentorshipSubscriptionStatusArrayValues: [MentorshipSubscriptionStatus, ...MentorshipSubscriptionStatus[]] = ["active","cancelled","expired"];
export const OrderStatusArrayValues: [OrderStatus, ...OrderStatus[]] = ["cancelled","completed","failed","pending","refunded"];
export const PrizeDistributionStatusArrayValues: [PrizeDistributionStatus, ...PrizeDistributionStatus[]] = ["distributed","not_applicable","pending"];
export const PrizeFundSourceArrayValues: [PrizeFundSource, ...PrizeFundSource[]] = ["enrollment","teacher_wallet"];
export const PromoCodeAppliesToArrayValues: [PromoCodeAppliesTo, ...PromoCodeAppliesTo[]] = ["all","bundles","courses","digital_products","live_tests","tests"];
export const QuestionTypeArrayValues: [QuestionType, ...QuestionType[]] = ["assertion_reason","comprehension","match_the_following","multiple_correct_mcq","numerical","single_correct_mcq"];
export const ReviewStatusArrayValues: [ReviewStatus, ...ReviewStatus[]] = ["approved","pending","rejected"];
export const SalesActivityTypeArrayValues: [SalesActivityType, ...SalesActivityType[]] = ["assignment_changed","call_logged","follow_up_changed","note_added","stage_changed"];
export const SalesContactSourceArrayValues: [SalesContactSource, ...SalesContactSource[]] = ["demo_request","signup"];
export const SalesStageArrayValues: [SalesStage, ...SalesStage[]] = ["converted","follow_up","new","not_interested","qualified"];
export const SubscriptionStatusArrayValues: [SubscriptionStatus, ...SubscriptionStatus[]] = ["active","cancelled","expired","pending"];
export const SupportMessageSenderTypeArrayValues: [SupportMessageSenderType, ...SupportMessageSenderType[]] = ["admin","teacher"];
export const SupportThreadStatusArrayValues: [SupportThreadStatus, ...SupportThreadStatus[]] = ["closed","open","resolved"];
export const TeacherTeamRoleArrayValues: [TeacherTeamRole, ...TeacherTeamRole[]] = ["manager","owner"];
export const TransactionStatusArrayValues: [TransactionStatus, ...TransactionStatus[]] = ["completed","failed","pending","refunded"];
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","student","teacher"];
export const WalletTransactionTypeArrayValues: [WalletTransactionType, ...WalletTransactionType[]] = ["prize_credit","prize_lock_refund","purchase_debit","withdrawal_debit"];
export const WithdrawalStatusArrayValues: [WithdrawalStatus, ...WithdrawalStatus[]] = ["cancelled","completed","failed","pending"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.